<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>23&nbsp; Marginal Structural Models – Analytical Epidemiology</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./references.html" rel="next">
<link href="./propensityscores.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-747bc48f972f7c4036e4d8e8c6d9e55a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script>
  window.MathJax = {
    loader: {load: ['[tex]/centernot']},
    tex: {
      macros: {
        A: "\\mathcal\{A\}",
        approxsim: "\\stackrel\{\\text\{approx\}\}\{\\sim\}",
        AR: "\\text\{AR\}",
        B: "\\mathcal\{B\}",
        Bernoulli: ["\\operatorname\{Bernoulli\}"],
        binomial: ["\\operatorname\{binomial\}"],
        C: "\\mathcal\{C\}",
        chisqH: "\\chi^2_\\text\{H\}",
        chisqP: "\\chi^2_\\text\{P\}",
        chisqPobs: "\\chi^2_\\text\{Pobs\}",
        cHR: "\\text\{cHR\}",
        CHR: "\\text\{CHR\}",
        cloglog: ["\\operatorname\{cloglog\}"],
        comp: "\\mathsf\{C\}",
        Cov: ["\\operatorname\{Cov\}"],
        crude: "\\text\{crude\}",
        D: "\\mathcal\{D\}",
        data: "\\text\{data\}",
        dif: "\\text\{d\}",
        Dminus: "\\text\{D\}^-",
        Dplus: "\\text\{D\}^+",
        E: ["\\operatorname\{\\mathbb\{E\}\}"],
        ESSR: "\\text\{ESSR\}",
        expit: ["\\operatorname\{expit\}"],
        given: ["\\, #1| \\, ", 1],
        HR: "\\text\{HR\}",
        indep: "\\perp\\!\\!\\!\\perp",
        indicator: "\\mathbb\{1\}",
        iptw: ["\\operatorname\{iptw\}"],
        ipw: ["\\operatorname\{ipw\}"],
        IRR: "\\text\{IRR\}",
        K: "\\mathcal\{K\}",
        logit: ["\\operatorname\{logit\}"],
        margins: "\\text\{margins\}",
        obs: "\\text\{obs\}",
        odds: ["\\operatorname\{odds\}"],
        OR: "\\text\{OR\}",
        pa: "\\text\{pa\}",
        PAR: "\\text\{PAR\}",
        pcrude: "p^*\_\\text\{crude\}",
        pmarg: "p\_\\text\{marg\}",
        Prstd: "\\Pr\\nolimits\_\\text\{std\}",
        ptrue: "p_\{\\text\{true\}\}",
        R: "\\mathcal\{R\}",
        RD: "\\text\{RD\}",
        RR: "\\text\{RR\}",
        sens: "\\text\{sens\}",
        siptw: ["\\operatorname\{siptw\}"],
        spec: "\\text\{spec\}",
        std: "\\text\{std\}",
        supp: ["\\operatorname\{supp\}"],
        tcens: "t^\\text\{cens\}",
        tentry: "t^\\text\{entry\}",
        tevent: "t^\\text\{event\}",
        texit: "t^\\text\{exit\}",
        Tminus: "\\text\{T\}^-",
        tonset: "t^\\text\{onset\}",
        Tplus: "\\text\{T\}^+",
        transpose: "\\mathsf{T}",
        trec: "t^\\text\{rec\}",
        true: "\\text\{true\}",
        twobytwo: "2 \\times 2",
        vand: "\\text\{ and \}",
        Var: ["\\operatorname\{Var\}"],
        Xminus: "\\text\{X\}^-",
        Xobs: "\\text\{X\}^\\text\{obs\}",
        Xplus: "\\text\{X\}^+"
      }
    }
  };
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./stratification.html">Epidemologic and Statistical Methods for Causal Inference</a></li><li class="breadcrumb-item"><a href="./marginalstructural.html"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Marginal Structural Models</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Analytical Epidemiology</a> 
        <div class="sidebar-tools-main">
    <a href="./Analytical-Epidemiology.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Defining and Measuring Disease Occurrence</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Probability, Random Variables, and Disease Occurrence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./condprob.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Conditional Probability and Diagnostic Tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlestimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Maximum Likelihood Estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Bayesian Estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./longitudinal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Longitudinal Data, Rates, and Counts</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./survival.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">One-Sample Survival Analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Study Design and Measures of Association</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./studydesign.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Cohort and Case-Control Studies</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./validity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Internal and External Validity</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cohort.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Measures of Association in Cohort Studies</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./survival2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Two-Sample Survival Analysis and the Cox Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./casecontrol.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Design and Analysis of Case-Control and Case-Cohort studies</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bayes2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Bayesian analysis of cohort and case-control studies</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Principles of Causal Inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./causality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Causality in Public Health</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./counterfactuals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Potential Outcomes and Attributable Risk</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dags.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Confounding and Selection Bias on DAGs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./swigs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Confounding and Selection Bias on SWIGs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./standardization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Causal Effects and Standardization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./geometry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Geometry of Causal Inference</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Epidemologic and Statistical Methods for Causal Inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stratification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Stratified Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./matching.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Matching in Cohort and Case-Control Studies</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./outcomereg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Multivariable Outcome Regression Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./propensityscores.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Propensity Scores</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./marginalstructural.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Marginal Structural Models</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Calculus</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#inverse-probability-of-treatment-weighting" id="toc-inverse-probability-of-treatment-weighting" class="nav-link active" data-scroll-target="#inverse-probability-of-treatment-weighting"><span class="header-section-number">23.1</span> Inverse probability of treatment weighting</a>
  <ul class="collapse">
  <li><a href="#stabilized-ipt-weights" id="toc-stabilized-ipt-weights" class="nav-link" data-scroll-target="#stabilized-ipt-weights"><span class="header-section-number">23.1.1</span> Stabilized IPT weights</a></li>
  <li><a href="#propensity-scores-and-ipt-weights" id="toc-propensity-scores-and-ipt-weights" class="nav-link" data-scroll-target="#propensity-scores-and-ipt-weights"><span class="header-section-number">23.1.2</span> Propensity scores and IPT weights</a></li>
  <li><a href="#ipt-weighting-and-standardization" id="toc-ipt-weighting-and-standardization" class="nav-link" data-scroll-target="#ipt-weighting-and-standardization"><span class="header-section-number">23.1.3</span> IPT weighting and standardization</a></li>
  </ul></li>
  <li><a href="#simpsons-paradox-reweighted" id="toc-simpsons-paradox-reweighted" class="nav-link" data-scroll-target="#simpsons-paradox-reweighted"><span class="header-section-number">23.2</span> Simpson’s paradox reweighted</a>
  <ul class="collapse">
  <li><a href="#standardized-risks" id="toc-standardized-risks" class="nav-link" data-scroll-target="#standardized-risks"><span class="header-section-number">23.2.1</span> Standardized risks</a></li>
  <li><a href="#pseudopopulation-based-on-unstabilized-iptw" id="toc-pseudopopulation-based-on-unstabilized-iptw" class="nav-link" data-scroll-target="#pseudopopulation-based-on-unstabilized-iptw"><span class="header-section-number">23.2.2</span> Pseudopopulation based on unstabilized IPTW</a></li>
  <li><a href="#pseudopopulation-based-on-stabilized-iptw" id="toc-pseudopopulation-based-on-stabilized-iptw" class="nav-link" data-scroll-target="#pseudopopulation-based-on-stabilized-iptw"><span class="header-section-number">23.2.3</span> Pseudopopulation based on stabilized IPTW</a></li>
  <li><a href="#pseudopopulation-based-on-iptw-for-the-treated" id="toc-pseudopopulation-based-on-iptw-for-the-treated" class="nav-link" data-scroll-target="#pseudopopulation-based-on-iptw-for-the-treated"><span class="header-section-number">23.2.4</span> Pseudopopulation based on IPTW for the treated</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./stratification.html">Epidemologic and Statistical Methods for Causal Inference</a></li><li class="breadcrumb-item"><a href="./marginalstructural.html"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Marginal Structural Models</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Marginal Structural Models</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>In summary, if there are no unmeasured confounders given data on <span class="math inline">\(L_0\)</span>, one can control confounding (due to <span class="math inline">\(L_0\)</span>) by modifying the crude analysis by weighting each subject <span class="math inline">\(i\)</span> by <span class="math inline">\(w_i\)</span>. The denominator of <span class="math inline">\(w_i\)</span> is informally the probability that a subject had his her own observed treatment. <span class="citation" data-cites="robins2000marginal">(<a href="references.html#ref-robins2000marginal" role="doc-biblioref">Robins, Hernán, and Brumback 2000</a>)</span></p>
</blockquote>
<p>We can calculate the causal effect of an exposure <span class="math inline">\(X\)</span> on a disease outcome <span class="math inline">\(D\)</span> by stratifying on a set of covariates <span class="math inline">\(C\)</span> sufficient to control confounding and selection bias, calculating the stratum-specific risks, and standardizing. The basic idea of standardization is to calculate the effect of treatment in a population where the exposed and the unexposed have the same distribution of <span class="math inline">\(C\)</span>. Without standardization, the risk of disease in each exposure group is: <span id="eq-observed"><span class="math display">\[
  \begin{aligned}
    &amp; \Pr(D = 1 \given{} X = x, S = 1) \nonumber \\
    &amp;\qquad = \sum_c \Pr(D = 1 \given{} C = c, X = 1, S = 1) \Pr(C = c \given{} X = x, S = 1),
  \end{aligned}
\tag{23.1}\]</span></span> where the sum is over the possible values <span class="math inline">\(c\)</span> of the confounder <span class="math inline">\(C\)</span>. Because of the term <span class="math inline">\(\Pr(C = c \given{} X = x, S = 1)\)</span> on the right, the distribution of <span class="math inline">\(C\)</span> can differ across exposure groups.</p>
<p>When we standardize, we replace <span class="math inline">\(\Pr(C = c \given{} X = x, S = 1)\)</span> in <a href="#eq-observed" class="quarto-xref">Equation&nbsp;<span>23.1</span></a> with a <span class="math inline">\(\Prstd(C = c)\)</span> that is the same in both exposure groups. The standardized risk of disease is <span id="eq-standardized"><span class="math display">\[
  \Prstd(D = 1 \given{} X = x)
  = \sum_c \Pr(D = 1 \given{} C = c, X = x, S = 1) \Prstd(C = c).
\tag{23.2}\]</span></span> When conditioning on <span class="math inline">\(C\)</span> is sufficient to control confounding and selection bias, this standardized risk can be interpreted as the causal risk of disease <span class="math inline">\(\Prstd(D^x = 1)\)</span> if we intervened to set <span class="math inline">\(X = x\)</span> in the standard population. The corresponding standardized risk differences, risk ratios, odds ratios, or cumulative hazard ratios are estimates of the causal effect of <span class="math inline">\(X\)</span> on <span class="math inline">\(D\)</span> in the standard population. These measures of causal effect can depend on the distribution of <span class="math inline">\(C\)</span> that we choose as the standard.</p>
<p>Standardization does not work well when the number of possible combinations of values of covariates in <span class="math inline">\(C\)</span> is large. <span class="citation" data-cites="truett1967multivariate">Truett, Cornfield, and Kannel (<a href="references.html#ref-truett1967multivariate" role="doc-biblioref">1967</a>)</span> gave an example where almost 600,000 participants would be needed to have a denominator of at least 10 in each of the <span class="math inline">\(3^{10} = 59{,}049\)</span> strata defined by 10 variables with three levels each. The bias-variance tradeoff is staring us in the face: If we let each level of <span class="math inline">\(C\)</span> define a separate stratum, we could end up with high variance in our risk estimates, which would lead to high variance in the standardized risks. If we group levels of <span class="math inline">\(C\)</span>, we might get residual confounding within these combined strata.</p>
<section id="inverse-probability-of-treatment-weighting" class="level2" data-number="23.1">
<h2 data-number="23.1" class="anchored" data-anchor-id="inverse-probability-of-treatment-weighting"><span class="header-section-number">23.1</span> Inverse probability of treatment weighting</h2>
<p>Another way to standardize is to weight each individual in the population and then calculate a marginal measure of association (i.e., a measure that is not conditional on <span class="math inline">\(C\)</span>) in the weighted population, which is often called the <strong>pseudopopulation</strong> <span class="citation" data-cites="horvitz1952generalization rosenbaum1987model robins2000marginal">(<a href="references.html#ref-horvitz1952generalization" role="doc-biblioref">Horvitz and Thompson 1952</a>; <a href="references.html#ref-rosenbaum1987model" role="doc-biblioref">Rosenbaum 1987</a>; <a href="references.html#ref-robins2000marginal" role="doc-biblioref">Robins, Hernán, and Brumback 2000</a>)</span>. In the pseudopopulation, there is no association between <span class="math inline">\(C\)</span> and <span class="math inline">\(X\)</span>, so all treatment groups have the same distribution of <span class="math inline">\(C\)</span> and the marginal measure of association has a causal interpretation like that from a randomized trial. It is important to note that this approach only works if conditioning on the covariates in <span class="math inline">\(C\)</span> is sufficient to control for confounding and selection bias.</p>
<p>To understand these weights, we will think of them in three steps. Suppose we have a study sample with <span class="math inline">\(n\)</span> individuals. If we weight each person by the inverse probability weight <span class="math display">\[
  \ipw(x, c)
  = \frac{1}{\Pr(X = x, C = c \given{} S = 1)},
\]</span> then the number of individuals with <span class="math inline">\(X = x\)</span> and <span class="math inline">\(C = c\)</span> in the pseudopopulation is <span class="math display">\[
  n \Pr(X = x, C = c \given{} S = 1) \frac{1}{\Pr(X = x, C = c \given{} S = 1)} = n,
\]</span> so all combinations of <span class="math inline">\(X\)</span> and <span class="math inline">\(C\)</span> are equally likely in the pseudopopulation. This creates a pseudopopulation that has a copy of the study sample within each combination of <span class="math inline">\(X\)</span> and <span class="math inline">\(C\)</span> , so there is no confounding of the association between treatment <span class="math inline">\(X\)</span> and death <span class="math inline">\(D\)</span> by <span class="math inline">\(C\)</span>. <a href="#tbl-wsimpson" class="quarto-xref">Table&nbsp;<span>23.1</span></a> shows the population from the example in <span class="citation" data-cites="simpson1951interpretation">Simpson (<a href="references.html#ref-simpson1951interpretation" role="doc-biblioref">1951</a>)</span> with weights <span class="math inline">\(\ipw(x, c)\)</span>. All combinations of treatment <span class="math inline">\(X\)</span> and biological sex <span class="math inline">\(C\)</span> have 52 individuals. In the pseudopopulation, there is no confounding of the association between treatment <span class="math inline">\(X\)</span> and death <span class="math inline">\(D\)</span> by biological sex: Within each biological sex, the probability of treatment is <span class="math inline">\(1 / 2\)</span>, so the pseudopopulation is like the population of a randomized trial.</p>
<div id="tbl-wsimpson" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-wsimpson-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;23.1: Simpson’s paradox data under different weights based on treatment (<span class="math inline">\(X\)</span>) and biological sex (<span class="math inline">\(C\)</span>).}
</figcaption>
<div aria-describedby="tbl-wsimpson-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<tbody>
<tr class="odd">
<td style="text-align: center;"></td>
<td colspan="2" style="text-align: center;"><strong>Male</strong></td>
<td colspan="2" style="text-align: center;"><strong>Female</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;">Weights</td>
<td style="text-align: center;">Treated</td>
<td style="text-align: center;">Untreated</td>
<td style="text-align: center;">Treated</td>
<td style="text-align: center;">Untreated</td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;">13</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">27</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\ipw(x, c)\)</span></td>
<td style="text-align: center;">52</td>
<td style="text-align: center;">52</td>
<td style="text-align: center;">52</td>
<td style="text-align: center;">52</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\iptw(x, c)\)</span></td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">32</td>
<td style="text-align: center;">32</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\siptw(x, c)\)</span></td>
<td style="text-align: center;">15.38</td>
<td style="text-align: center;">4.62</td>
<td style="text-align: center;">24.62</td>
<td style="text-align: center;">7.38</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The next step is to make the pseudopopulation have the same distribution of <span class="math inline">\(C\)</span> has the study sample. The <strong>inverse probability of treatment weight</strong> (IPT weight or IPTW) is <span id="eq-iptw"><span class="math display">\[
  \iptw(x, c)
  = \frac{\Pr(C = c \given{} S = 1)}{\Pr(X = x, C = c \given{} S = 1)}
  = \frac{1}{\Pr(X = x \given{} C = c, S = 1)}.
\tag{23.3}\]</span></span> In the resulting pseudopopulation, the number of individuals with <span class="math inline">\(X = x\)</span> and <span class="math inline">\(C = c\)</span> is <span class="math display">\[
  n \Pr(X = x, C = c \given{} S = 1)
    \frac{\Pr(C = c \given{} S = 1)}{\Pr(X = x, C = c \given{} S = 1)}
  = n \Pr(C = c \given{} S = 1),
\]</span> so this the pseudopopulation has a copy of the study sample within each treatment group. <a href="#tbl-wsimpson" class="quarto-xref">Table&nbsp;<span>23.1</span></a> shows the pseudopopulation based on <span class="math inline">\(\iptw(x, c)\)</span> in the example from <span class="citation" data-cites="simpson1951interpretation">Simpson (<a href="references.html#ref-simpson1951interpretation" role="doc-biblioref">1951</a>)</span>. Each treatment group has 32 females and 20 males, which matches the sex distribution in the study sample. In the pseudopopulation, there is no confounding of the association between treatment <span class="math inline">\(X\)</span> and death <span class="math inline">\(D\)</span> by biological sex <span class="math inline">\(C\)</span>: Within each biological sex, the probability of treatment is <span class="math inline">\(1 / 2\)</span>. Again, the pseudopopulation is like the population of a randomized trial.</p>
<p>A common source of confusion is to think that the IPTW is the inverse probability of being treated or exposed, which is the meaning of “probability of treatment” in the context of the propensity score from <a href="propensityscores.html" class="quarto-xref"><span>Chapter 22</span></a>. For inverse probability of treatment weights, “probability of treatment” means the probability of receiving the treatment that you got. If you are exposed, it is the conditional probability of being exposed given your covariate values. If you are unexposed, it is the conditional probability of being unexposed given your covariate values.</p>
<section id="stabilized-ipt-weights" class="level3" data-number="23.1.1">
<h3 data-number="23.1.1" class="anchored" data-anchor-id="stabilized-ipt-weights"><span class="header-section-number">23.1.1</span> Stabilized IPT weights</h3>
<p>Finally, we can make the pseudopopulation have the same distribution of both <span class="math inline">\(X\)</span> and <span class="math inline">\(C\)</span> as the study sample while ensuring that they remain independent. The <strong>stabilized IPT weight</strong> is <span id="eq-siptw"><span class="math display">\[
  \begin{aligned}
    \siptw(x, c)
    &amp;= \Pr(X = x \given{} S = 1) \times \iptw(x, c) \\
    &amp;= \frac{\Pr(X = x \given{} S = 1)}{\Pr(X = x \given{} C = c, S = 1)} \\
    &amp;= \frac{\Pr(X = x \given{} S = 1) \Pr(C = c \given{} S = 1)}{\Pr(X = x, C = c \given{} S = 1)}.
  \end{aligned}
\tag{23.4}\]</span></span> In the final expression, the denominator is the probability that <span class="math inline">\(X = x\)</span> and <span class="math inline">\(C = c\)</span> in the study sample and the numerator <span class="math display">\[
  \Pr(X = x \given{} S = 1) \Pr(C = c \given{} S = 1)
\]</span> is the probability that <span class="math inline">\(X = x\)</span> and <span class="math inline">\(C = c\)</span> if <span class="math inline">\(X\)</span> and <span class="math inline">\(C\)</span> are independent but have the same marginal distributions as in the study sample. If <span class="math inline">\(X\)</span> and <span class="math inline">\(C\)</span> are independent in the study sample, the stabilized weights equal one and the pseudopopulation is a copy of the study sample.</p>
<p><a href="#tbl-wsimpson" class="quarto-xref">Table&nbsp;<span>23.1</span></a> shows the pseudopopulation based on <span class="math inline">\(\siptw(x, c)\)</span> for the example in <span class="citation" data-cites="simpson1951interpretation">Simpson (<a href="references.html#ref-simpson1951interpretation" role="doc-biblioref">1951</a>)</span>. As in the study sample, the pseudopopulation has 32 females, 20 males, 40 treated individuals, and 12 untreated individuals. In the pseudopopulation, there is no confounding of the association between treatment <span class="math inline">\(X\)</span> and death <span class="math inline">\(D\)</span> by biological sex: Within each biological sex, the probability of treatment is <span class="math inline">\(40 / 52 \approx 0.769\)</span>, which is the overall probability of treatment in the study sample.</p>
<p>In simple examples where <span class="math inline">\(C\)</span> defines a small number of strata, both unstabilized and stabilized IPT weights give exactly the same results. When a regression model<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> is used to estimate the risk of disease in the pseudopopulation as is done in <strong>marginal structural models</strong> <span class="citation" data-cites="robins2000marginal hernan2000marginal">(<a href="references.html#ref-robins2000marginal" role="doc-biblioref">Robins, Hernán, and Brumback 2000</a>; <a href="references.html#ref-hernan2000marginal" role="doc-biblioref">Hernán, Brumback, and Robins 2000</a>)</span>, the stabilized weights usually give smaller standard errors. In practice, the stabilized weights should always be used.</p>
</section>
<section id="propensity-scores-and-ipt-weights" class="level3" data-number="23.1.2">
<h3 data-number="23.1.2" class="anchored" data-anchor-id="propensity-scores-and-ipt-weights"><span class="header-section-number">23.1.2</span> Propensity scores and IPT weights</h3>
<p>The propensity score <span class="math display">\[
  \pi(c) = \Pr(X = 1 \given{} C = c, S = 1)
\]</span> is the conditional probability of being treated given <span class="math inline">\(C = c\)</span> <span class="citation" data-cites="rosenbaum1983central">(<a href="references.html#ref-rosenbaum1983central" role="doc-biblioref">Rosenbaum and Rubin 1983</a>)</span>. In <a href="propensityscores.html" class="quarto-xref"><span>Chapter 22</span></a>, we saw that propensity scores can be used control confounding and selection bias via matching or stratifying by the propensity score or by include the propensity score as a predictor in an outcome regression model. They can also be used to calculate inverse probability of treatment weights. However, please note the difference in the definition of “treatment” in the two settings:</p>
<ul>
<li><p>For propensity scores, “treatment” means being in the group defined as treated or exposed.</p></li>
<li><p>For IPT weights, “treatment” means the treatment that each individual received whether they are in the treated (or exposed) group or the untreated (or unexposed) group.</p></li>
</ul>
<p>The unstabilized IPT weight is <span class="math display">\[
  \frac{1}{\Pr(X = x \given{} C = c, S = 1)} =
  \begin{cases}
    \frac{1}{\pi(c)}      &amp;\text{for a treated individual,}\\[4pt]
    \frac{1}{1 - \pi(c)}  &amp;\text{for an untreated undividual},
  \end{cases}
\]</span> where <span class="math inline">\(\pi(c) = Pr(X = 1 \given{} C = c, S = 1)\)</span> is the propensity score. The stabilized IPT weight is <span class="math display">\[
  \frac{\Pr(X = x \given{} S = 1)}{\Pr(X = x \given{} C = c, S = 1)} =
  \begin{cases}
    \frac{\Pr(X = 1)}{\pi(c)}       &amp;\text{for a treated individual,}\\[4pt]
    \frac{\Pr(X = 0)}{1 - \pi(c)}   &amp;\text{for an untreated undividual}.
  \end{cases}
\]</span></p>
</section>
<section id="ipt-weighting-and-standardization" class="level3" data-number="23.1.3">
<h3 data-number="23.1.3" class="anchored" data-anchor-id="ipt-weighting-and-standardization"><span class="header-section-number">23.1.3</span> IPT weighting and standardization</h3>
<p>Let <span class="math inline">\(\Pr()\)</span> denote probabilities in the eligible population, and let <span class="math inline">\(\Pr^*()\)</span> denote probabilities calculated in the pseudupopulation created by the stabilized IPT weights. When exchangeability (no confounding) and the analytic cohort condition (no selection bias) hold given <span class="math inline">\(C\)</span>, we have <span class="math display">\[
    \Pr(D^x = 1 \given{} C = c) \nonumber \\
    = \Pr(D = 1 \given{} X = x, C = c, S = 1)
\]</span> by conditional exchangeability given <span class="math inline">\(C\)</span>, the analytic cohort condition given <span class="math inline">\(C\)</span>, and consistency (see <a href="standardization.html#eq-marginal-causal" class="quarto-xref">Equation&nbsp;<span>17.4</span></a>). Up to sampling variation, the conditional risk of disease given <span class="math inline">\(X = x\)</span> and <span class="math inline">\(C = c\)</span> in the study sample equals the causal risk that we would get in the <span class="math inline">\(C = c\)</span> stratum of the eligible population if we intervened to set <span class="math inline">\(X = x\)</span>. In the pseudopopulation created by the weights <span class="math inline">\(w(x, c)\)</span>, the conditional risk of death given <span class="math inline">\(X = x\)</span> and <span class="math inline">\(C = c\)</span> is <span class="math display">\[
  \begin{aligned}
    \Pr\nolimits^*(D = 1 \given{} X = x, C = c)
    &amp;= \frac{\Pr^*(D = 1, X = x, C = c)}{\Pr^*(X = x, C = c)} \\
    &amp;= \frac{\Pr(D = 1, X = x, C = c \given{} S = 1)
      \times w(x, c)}{\Pr(X = x, C = c \given{} S = 1) \times w(x, c)} \\
    &amp;= \Pr(D = 1 \given{} X = x, C = c, S = 1)
  \end{aligned}
\]</span> where <span class="math inline">\(w(x, c)\)</span> could be the stabilized IPT weights, unstabilized IPT weights, or any other set of weights that depends only on <span class="math inline">\(x\)</span> and <span class="math inline">\(c\)</span>. Combining these results, we get <span class="math display">\[
  \Pr(D^x = 1 \given{} C = c)
  = \Pr\nolimits^*(D = 1 \given{} X = x, C = c).
\]</span> Up to sampling variation, the conditional risks of disease given <span class="math inline">\(X\)</span> and <span class="math inline">\(C\)</span> in the pseudopopulation equal the conditional causal risks given <span class="math inline">\(C\)</span> that would occur in the eligible population if we intervened to set <span class="math inline">\(X = x\)</span>.</p>
<p>The marginal risk of disease given <span class="math inline">\(X = x\)</span> in the pseudopopulation is <span class="math display">\[
  \begin{aligned}
    \Pr\nolimits^*(D = 1 \given{} X = x)
    &amp;= \sum_c \Pr\nolimits^*(D = 1 \given{} X = x, C = c) \Pr\nolimits^*(C = c) \\
    &amp;= \sum_c \Pr(D = 1 \given{} X = x, C = c, S = 1) \Pr(C = c \given{} S = 1).
  \end{aligned}
\]</span> The last expression is the risk of disease standardized to the distribution of <span class="math inline">\(C\)</span> in the study sample. Up to sampling variation, this standardized risk equals the causal risk of disease in the study sample if we intervened to set <span class="math inline">\(X = x\)</span>. Using <span class="math inline">\(\Pr^*(D = 1 \given{} X = 1)\)</span> and <span class="math inline">\(\Pr^*(D = 1 \given{} X = 0)\)</span>, we can calculate the standarized risk difference, risk ratio, odds ratio, or cumulative hazard ratio for the study sample. The same result holds if we use the unstabilized weights. If conditioning on <span class="math inline">\(C\)</span> is sufficient to control confounding and selection bias, these can be interpreted as causal risks and measures of causal effect.</p>
<p>Inverse probability weighting can be used to standardize to any distribution of <span class="math inline">\(C\)</span> <span class="citation" data-cites="sato2003marginal">(<a href="references.html#ref-sato2003marginal" role="doc-biblioref">Sato and Matsuyama 2003</a>)</span>. To get a measure of association standardized to a distribution <span class="math inline">\(\Prstd(C = c)\)</span>, we can use the weights <span id="eq-wstd"><span class="math display">\[
  w_\std(x, c)
  = \frac{\Prstd(C = c)}{\Pr(X = x \given{} C = c, S = 1)}
  = \frac{\Prstd(C = c) \Pr(X = x \given{} S = 1)}{\Pr(X = x, C = c \given{} S = 1)}.
\tag{23.5}\]</span></span> This creates a pseudopopulation with the standard distribution of <span class="math inline">\(C\)</span> and the same distribution of <span class="math inline">\(X\)</span> as the study sample. If we let <span class="math inline">\(\Prstd(C = c) = \Pr(C = c \given S = 1)\)</span>, then we get the stabilized IPT weights. Because these weights depend only on <span class="math inline">\(X\)</span> and <span class="math inline">\(C\)</span>, the conditional risk of disease given <span class="math inline">\(X\)</span> and <span class="math inline">\(C\)</span> is the same in the pseudopopulation and the study sample. Because the numerator of the weight is a product of a probability involving only <span class="math inline">\(X\)</span> and a probability involving only <span class="math inline">\(C\)</span>, <span class="math inline">\(X\)</span> and <span class="math inline">\(C\)</span> are independent in the pseudopopulation. Let <span class="math inline">\(\Pr^*()\)</span> represent probabilities in the pseudopopulation created by these weights. The marginal risk of disease given <span class="math inline">\(X = x\)</span> in the pseudopopulation is <span class="math display">\[
  \begin{aligned}
    \Pr\nolimits^*(D = 1 \given{} X = x)
    &amp;= \sum_c \Pr\nolimits^*(D = 1 \given{} X = x, C = c)
      \Pr\nolimits^*(C = c \given{} X = x) \\
    &amp;= \sum_c \Pr(D = 1 \given{} X = x, C = c, S = 1) \Prstd(C = c)
  \end{aligned}
\]</span> because <span class="math inline">\(\Pr^*(C = c \given{} X = x) = \Prstd(C = c)\)</span> in all treatment groups. As before, we can calculate standardized risks in the study sample by calculating marginal risks in the pseudopopulation.</p>
<p>This approach can be used to estimate causal effects in the treated, in the controls, or in the study sample. If we let <span class="math inline">\(\Prstd(C = c) = \Pr(C = c \given{} X = 1, S = 1)\)</span> in <a href="#eq-wstd" class="quarto-xref">Equation&nbsp;<span>23.5</span></a>, then we get the weights <span class="math display">\[
  w^*_\text{treated} =
  \begin{cases}
    \frac{\pi(c)}{1 - \pi(c)} = \frac{\iptw(0, c)}{\iptw(1, c)} &amp;\text{if } x = 0, \\
    1                                                           &amp;\text{if } x = 1.
  \end{cases}
\]</span> If we let <span class="math inline">\(\Prstd(C = c) = \Pr(C = c \given{} X = 0, S = 1)\)</span>, then we get the weights <span class="math display">\[
  w^*_\text{treated} =
  \begin{cases}
    \frac{1 - \pi(c)}{\pi(c)} = \frac{\iptw(1, c)}{\iptw(0, c)} &amp;\text{if } x = 0, \\
    1                                                           &amp;\text{if } x = 1.
  \end{cases}
\]</span> In a cohort study where selection depends on exposure, the conditional distribution of <span class="math inline">\(C\)</span> given <span class="math inline">\(X\)</span> is more scientifically meaningful than the marginal distribution of <span class="math inline">\(C\)</span> in the study sample.</p>
</section>
</section>
<section id="simpsons-paradox-reweighted" class="level2" data-number="23.2">
<h2 data-number="23.2" class="anchored" data-anchor-id="simpsons-paradox-reweighted"><span class="header-section-number">23.2</span> Simpson’s paradox reweighted</h2>
<p>To illustrate the use of IPT weights, we will use them to analyze the example of confounding <span class="citation" data-cites="simpson1951interpretation">Simpson (<a href="references.html#ref-simpson1951interpretation" role="doc-biblioref">1951</a>)</span>. The <a href="dags.html#tbl-simpson" class="quarto-xref">Table&nbsp;<span>15.1</span></a> shows the number of deaths among males, among females, and in both sexes. The effect of treatment is confounded by sex because women are more likely to be treated and more likely to die. Treatment reduces the risk of death within each sex, but it appears to have no marginal effect on risk of death in the study sample.</p>
<!-- ::: {#tbl-simpson-stratified}
  \begin{tabular}{c|cc|cc|cc}
    \toprule
    \multicolumn{1}{c}{} & \multicolumn{2}{|c|}{\textbf{Male}} & \multicolumn{2}{|c|}{\textbf{Female}} & \multicolumn{2}{|c}{\textbf{Combined}} \\
              & Treated & Untreated & Treated & Untreated & Treated & Untreated \\
    \midrule
    Dead      & 5         & 3       & 15        & 3       & 20      & 6\\
    Alive     & 8         & 4       & 12        & 2       & 20      & 6 \\
    \bottomrule
  \end{tabular}
  \caption{Simpson's paradox data stratified by sex (left) and unstratified (right).}
::: -->
<section id="standardized-risks" class="level3" data-number="23.2.1">
<h3 data-number="23.2.1" class="anchored" data-anchor-id="standardized-risks"><span class="header-section-number">23.2.1</span> Standardized risks</h3>
<p>The proportion male in the study sample is <span class="math inline">\(20 / 52 \approx 0.385\)</span>, and the proportion female is <span class="math inline">\(32 / 52 \approx 0.555\)</span>. The conditional risks of death given treatment and biological sex are given in <a href="standardization.html#sec-simpson-cond" class="quarto-xref"><span>Section 17.3.2</span></a>. If we use the distribution of biological sex in the study sample as out standard population, the standardized risk of death in the treated is <span class="math display">\[
  \frac{5}{13} \times \frac{20}{52} + \frac{15}{27} \times \frac{32}{52}
  \approx 0.490
\]</span> and the standardized risk of death in the untreated is <span class="math display">\[
  \frac{3}{7} \times \frac{20}{52} + \frac{3}{5} \times \frac{32}{52}
  \approx 0.534.
\]</span> We could use these risks to calculate measures of associaton such as a risk difference, risk ratio, odds ratio, or cumulative hazard ratio. Assuming the DAG in <a href="dags.html#fig-simpson-dag" class="quarto-xref">Figure&nbsp;<span>15.6</span></a> is true, these are unbiased estimates of the causal risk that would occur if we intervened to set <span class="math inline">\(X = 1\)</span> or <span class="math inline">\(X = 0\)</span>, respectively, in the study sample.</p>
</section>
<section id="pseudopopulation-based-on-unstabilized-iptw" class="level3" data-number="23.2.2">
<h3 data-number="23.2.2" class="anchored" data-anchor-id="pseudopopulation-based-on-unstabilized-iptw"><span class="header-section-number">23.2.2</span> Pseudopopulation based on unstabilized IPTW</h3>
<p>Among males, the probability of being treated is <span class="math inline">\(13 / 20 = 0.65\)</span>. The unstabilized IPT weight for treated males is <span class="math display">\[
  \iptw(1, \text{male})
  = \frac{20}{13}
  \approx 1.54,
\]</span> and the unstabilized IPT weight for untreated males is <span class="math display">\[
  \iptw(0, \text{male})
  = \frac{20}{7}
  \approx 2.86.
\]</span> Among females, the probability of being treated is <span class="math inline">\(27 / 32 \approx 0.84\)</span>. The unstabilized IPT weight for treated females is <span class="math display">\[
  \iptw(1, \text{female})
  = \frac{32}{27}
  \approx 1.19,
\]</span> and the unstabilized IPT weight for untreated females is <span class="math display">\[
  \iptw(0, \text{female})
  = \frac{32}{5}
  = 6.4.
\]</span> The resulting pseudopopulation is shown in <a href="#tbl-pseudo-unstabilized" class="quarto-xref">Table&nbsp;<span>23.2</span></a>. There are 52 treated people and 52 untreated people, and there are 20 males and 32 females within each treatment group.</p>
<div id="tbl-pseudo-unstabilized" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pseudo-unstabilized-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;23.2: Pseudopopulation created by the unstabilized IPT weights
</figcaption>
<div aria-describedby="tbl-pseudo-unstabilized-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<tbody>
<tr class="odd">
<td style="text-align: center;"></td>
<td colspan="2" style="text-align: center;"><strong>Male</strong></td>
<td colspan="2" style="text-align: center;"><strong>Female</strong></td>
<td colspan="2" style="text-align: center;"><strong>Combined</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;">Treated</td>
<td style="text-align: center;">Untreated</td>
<td style="text-align: center;">Treated</td>
<td style="text-align: center;">Untreated</td>
<td style="text-align: center;">Treated</td>
<td style="text-align: center;">Untreated</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Dead</td>
<td style="text-align: center;">7.69</td>
<td style="text-align: center;">8.57</td>
<td style="text-align: center;">17.78</td>
<td style="text-align: center;">19.2</td>
<td style="text-align: center;">25.47</td>
<td style="text-align: center;">27.77</td>
</tr>
<tr class="even">
<td style="text-align: center;">Alive</td>
<td style="text-align: center;">12.31</td>
<td style="text-align: center;">11.43</td>
<td style="text-align: center;">14.22</td>
<td style="text-align: center;">12.8</td>
<td style="text-align: center;">26.53</td>
<td style="text-align: center;">24.23</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>In this pseudopopulation, the marginal risk of death in the treated is <span class="math display">\[
  \frac{20 / 13 \times 5 + 32 / 27 \times 15}
    {20 / 13 \times (5 + 8) + 32 / 27 \times (15 + 12)}
  \approx \frac{25.47}{52}
  \approx 0.490.
\]</span> The marginal risk of death in the untreated is <span class="math display">\[
  \frac{\sfrac{20}{7} \times 3 + \sfrac{32}{5} \times 3}
  {\sfrac{20}{7} \times (3 + 4) + \sfrac{32}{5} \times (3 + 2)}
  \approx \frac{27.77}{52} \approx 0.534.
\]</span> These are exactly the same as the risks of death standardized to the sex distribution in the study sample. Thus, all possible measures of association are also the same.</p>
</section>
<section id="pseudopopulation-based-on-stabilized-iptw" class="level3" data-number="23.2.3">
<h3 data-number="23.2.3" class="anchored" data-anchor-id="pseudopopulation-based-on-stabilized-iptw"><span class="header-section-number">23.2.3</span> Pseudopopulation based on stabilized IPTW</h3>
<p>Among males, the probability of being treated is <span class="math inline">\(13 / 20 = 0.65\)</span>. The treated proportion of the study sample is <span class="math inline">\(40 / 52 \approx 0.77\)</span>, and the untreated portion is <span class="math inline">\(12 / 52 \approx 0.23\)</span>. The stabilized IPT weight for treated males is <span class="math display">\[
  \siptw(1, \text{male})
  = \frac{40}{52} \times \frac{20}{13}
  \approx 1.18,
\]</span> and the unstabilized IPT weight for untreated males is <span class="math display">\[
  \siptw(0, \text{male})
  = \frac{12}{52} \times \frac{20}{7}
  \approx 0.66.
\]</span> Among females, the probability of being treated is <span class="math inline">\(27 / 32 \approx 0.84\)</span>. The unstabilized IPT weight for treated females is <span class="math display">\[
  \siptw(1, \text{female})
  = \frac{40}{52} \times \frac{32}{27}
  \approx 0.91,
\]</span> and the unstabilized IPT weight for untreated females is <span class="math display">\[
  \siptw(0, \text{female})
  = \frac{12}{52} \times \frac{32}{5}
  = 1.48.
\]</span> The resulting pseudopopulation is shown in <a href="#tbl-pseudo-stabilized" class="quarto-xref">Table&nbsp;<span>23.3</span></a>. Ignoring small errors introduced by rounding to two decimal places, there are a total of 52 people of which 26 are treated, 26 are untreated, 20 are male, and 32 are female. To three decimal points, there are 5.917 treated males and 13.675 treated females who died, which produces a total of 19.592 treated deaths.</p>
<div id="tbl-pseudo-stabilized" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pseudo-stabilized-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;23.3: Pseudopopulation created by the stabilized IPT weights
</figcaption>
<div aria-describedby="tbl-pseudo-stabilized-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<tbody>
<tr class="odd">
<td style="text-align: center;"></td>
<td colspan="2" style="text-align: center;"><strong>Male</strong></td>
<td colspan="2" style="text-align: center;"><strong>Female</strong></td>
<td colspan="2" style="text-align: center;"><strong>Combined</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;">Treated</td>
<td style="text-align: center;">Untreated</td>
<td style="text-align: center;">Treated</td>
<td style="text-align: center;">Untreated</td>
<td style="text-align: center;">Treated</td>
<td style="text-align: center;">Untreated</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Dead</td>
<td style="text-align: center;">5.92</td>
<td style="text-align: center;">1.98</td>
<td style="text-align: center;">13.68</td>
<td style="text-align: center;">4.43</td>
<td style="text-align: center;">19.59</td>
<td style="text-align: center;">6.41</td>
</tr>
<tr class="even">
<td style="text-align: center;">Alive</td>
<td style="text-align: center;">9.47</td>
<td style="text-align: center;">2.64</td>
<td style="text-align: center;">10.94</td>
<td style="text-align: center;">2.95</td>
<td style="text-align: center;">20.41</td>
<td style="text-align: center;">5.59</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>In the pseudopopulation created by the stabilized weights, marginal risk of death in the treated is <span class="math display">\[
  \frac{(40 / 52 \times 20 / 13) \times 5 + (40 / 52 \times 32 / 27) \times 15}
  {(40 / 52 \times 20 / 13) \times (5 + 8)
    + (40 / 52 \times 32 / 27) \times (15 + 12)}
  \approx \frac{19.59}{40} \approx 0.490
\]</span> and the marginal risk of death in the untreated is <span class="math display">\[
  \frac{(12 / 52 \times 20 / 7) \times 3 + (12 / 52 \times 32 / 5) \times 3}
  {(12 / 52 \times 20 / 7) \times (3 + 4)
    + (12 / 52 \times 32 / 5) \times (3 + 2)}
  \approx \frac{6.41}{12} \approx 0.534.
\]</span> Because the probability of each treatment status cancels out of the numerator and denominator, these risks are exactly the same as the unstabilized IPTW risks and the standardized risks. It follows that all three methods produce exactly the same measures of association in this simple example.</p>
<p>The stabilized weights go from <span class="math inline">\(0.66\)</span> (untreated men) to <span class="math inline">\(1.48\)</span> (untreated women), whereas the unstabilized weights go from <span class="math inline">\(0.60\)</span> (treated women) to <span class="math inline">\(3.20\)</span> (untreated women). True to their name, the stabilized weights vary less than the unstabilized weights. The pseudopopulation generated by the unstabilized weights had 104 individuals, but the pseudopopulation generated by the stabilized weights had 52 individuals just like the original study sample. Thus, the average unstabilized weight equals 2 and the average stabilized weight equals 1.</p>
</section>
<section id="pseudopopulation-based-on-iptw-for-the-treated" class="level3" data-number="23.2.4">
<h3 data-number="23.2.4" class="anchored" data-anchor-id="pseudopopulation-based-on-iptw-for-the-treated"><span class="header-section-number">23.2.4</span> Pseudopopulation based on IPTW for the treated</h3>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-hernan2000marginal" class="csl-entry" role="listitem">
Hernán, Miguel Ángel, Babette Brumback, and James M Robins. 2000. <span>“Marginal Structural Models to Estimate the Causal Effect of Zidovudine on the Survival of <span>HIV</span>-Positive Men.”</span> <em>Epidemiology</em> 11: 561–70.
</div>
<div id="ref-horvitz1952generalization" class="csl-entry" role="listitem">
Horvitz, Daniel G, and Donovan J Thompson. 1952. <span>“A Generalization of Sampling Without Replacement from a Finite Universe.”</span> <em>Journal of the American Statistical Association</em> 47 (260): 663–85.
</div>
<div id="ref-robins2000marginal" class="csl-entry" role="listitem">
Robins, James M, Miguel Ángel Hernán, and Babette Brumback. 2000. <span>“Marginal Structural Models and Causal Inference in Epidemiology.”</span> <em>Epidemiology</em> 11: 550–60.
</div>
<div id="ref-rosenbaum1987model" class="csl-entry" role="listitem">
Rosenbaum, Paul R. 1987. <span>“Model-Based Direct Adjustment.”</span> <em>Journal of the American Statistical Association</em> 82 (398): 387–94.
</div>
<div id="ref-rosenbaum1983central" class="csl-entry" role="listitem">
Rosenbaum, Paul R, and Donald B Rubin. 1983. <span>“The Central Role of the Propensity Score in Observational Studies for Causal Effects.”</span> <em>Biometrika</em> 70 (1): 41–55.
</div>
<div id="ref-sato2003marginal" class="csl-entry" role="listitem">
Sato, Tosiya, and Yutaka Matsuyama. 2003. <span>“Marginal Structural Models as a Tool for Standardization.”</span> <em>Epidemiology</em> 14 (6): 680–86.
</div>
<div id="ref-simpson1951interpretation" class="csl-entry" role="listitem">
Simpson, Edward H. 1951. <span>“The Interpretation of Interaction in Contingency Tables.”</span> <em>Journal of the Royal Statistical Society: Series B (Methodological)</em> 13 (2): 238–41.
</div>
<div id="ref-truett1967multivariate" class="csl-entry" role="listitem">
Truett, Jeanne, Jerome Cornfield, and William Kannel. 1967. <span>“A Multivariate Analysis of the Risk of Coronary Heart Disease in Framingham.”</span> <em>Journal of Chronic Diseases</em> 20 (7): 511–24.
</div>
</div>
</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p> Specifically, a nonsaturated regression model. A saturated regression model is one where there is each unique combination of the covariates has an estimated coefficient or intercept. For example, a model for <span class="math inline">\(k\)</span> groups that has <span class="math inline">\(k - 1\)</span> dummy variables is saturated.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./propensityscores.html" class="pagination-link" aria-label="Propensity Scores">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Propensity Scores</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./references.html" class="pagination-link" aria-label="References">
        <span class="nav-page-text">References</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>