<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>8&nbsp; Internal and External Validity – Analytical Epidemiology</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./cohort.html" rel="next">
<link href="./studydesign.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-747bc48f972f7c4036e4d8e8c6d9e55a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script>
  window.MathJax = {
    tex: {
      macros: {
        A: "\\mathcal\{A\}",
        approxsim: "\\stackrel\{\\text\{approx\}\}\{\\sim\}",
        B: "\\mathcal\{B\}",
        Bernoulli: ["\\operatorname\{Bernoulli\}"],
        binomial: ["\\operatorname\{binomial\}"],
        C: "\\mathcal\{C\}",
        chisqH: "\\chi^2_\\text\{H\}",
        chisqP: "\\chi^2_\\text\{P\}",
        chisqPobs: "\\chi^2_\\text\{Pobs\}",
        cloglog: ["\\operatorname\{cloglog\}"],
        comp: "\\mathsf\{C\}",
        Cov: ["\\operatorname\{Cov\}"],
        D: "\\mathcal\{D\}",
        data: "\\text\{data\}",
        dif: "\\text\{d\}",
        Dminus: "\\text\{D\}^-",
        Dplus: "\\text\{D\}^+",
        E: ["\\operatorname\{\\mathbb\{E\}\}"],
        ESSR: "\\text\{ESSR\}",
        expit: ["\\operatorname\{expit\}"],
        given: ["\\, #1| \\, ", 1],
        HR: "\\text\{HR\}",
        indep: "\\perp\\!\\!\\!\\perp",
        indicator: "\\mathbb\{1\}",
        IRR: "\\text\{IRR\}",
        K: "\\mathcal\{K\}",
        logit: ["\\operatorname\{logit\}"],
        margins: "\\text\{margins\}",
        obs: "\\text\{obs\}",
        odds: ["\\operatorname\{odds\}"],
        OR: "\\text\{OR\}",
        ptrue: "p_\{\\text\{true\}\}",
        R: "\\mathcal\{R\}",
        RD: "\\text\{RD\}",
        RR: "\\text\{RR\}",
        sens: "\\text\{sens\}",
        spec: "\\text\{spec\}",
        supp: ["\\operatorname\{supp\}"],
        tcens: "t^\\text\{cens\}",
        tentry: "t^\\text\{entry\}",
        tevent: "t^\\text\{event\}",
        texit: "t^\\text\{exit\}",
        Tminus: "\\text\{T\}^-",
        tonset: "t^\\text\{onset\}",
        Tplus: "\\text\{T\}^+",
        transpose: "\\mathsf{T}",
        trec: "t^\\text\{rec\}",
        true: "\\text\{true\}",
        twobytwo: "2 \\times 2",
        vand: "\\text\{ and \}",
        Var: ["\\operatorname\{Var\}"],
        Xminus: "\\text\{X\}^-",
        Xobs: "\\text\{X\}^\\text\{obs\}",
        Xplus: "\\text\{X\}^+"
      }
    }
  };
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./studydesign.html">Study Design and Measures of Association</a></li><li class="breadcrumb-item"><a href="./validity.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Internal and External Validity</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Analytical Epidemiology</a> 
        <div class="sidebar-tools-main">
    <a href="./Analytical-Epidemiology.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Defining and Measuring Disease Occurrence</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Probability, Random Variables, and Disease Occurrence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./condprob.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Conditional Probability and Diagnostic Tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlestimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Maximum Likelihood Estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Bayesian Estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./longitudinal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Longitudinal Data, Rates, and Counts</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./survival.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">One-Sample Survival Analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Study Design and Measures of Association</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./studydesign.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Cohort and Case-Control Studies</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./validity.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Internal and External Validity</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cohort.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Measures of Association in Cohort Studies</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./survival2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Two-Sample Survival Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./casecontrol.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Measures of association in case-control studies</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bayes2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Bayesian analysis of cohort and case-control studies</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Principles of Causal Inference</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Epidemologic and Statistical Methods for Causal Inference</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Calculus</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#misclassification" id="toc-misclassification" class="nav-link active" data-scroll-target="#misclassification"><span class="header-section-number">8.1</span> Misclassification</a>
  <ul class="collapse">
  <li><a href="#nondifferential-misclassification-of-disease" id="toc-nondifferential-misclassification-of-disease" class="nav-link" data-scroll-target="#nondifferential-misclassification-of-disease"><span class="header-section-number">8.1.1</span> Nondifferential misclassification of disease</a></li>
  <li><a href="#nondifferential-misclassification-of-exposure" id="toc-nondifferential-misclassification-of-exposure" class="nav-link" data-scroll-target="#nondifferential-misclassification-of-exposure"><span class="header-section-number">8.1.2</span> Nondifferential misclassification of exposure</a></li>
  <li><a href="#simultaneous-nondifferential-misclassification" id="toc-simultaneous-nondifferential-misclassification" class="nav-link" data-scroll-target="#simultaneous-nondifferential-misclassification"><span class="header-section-number">8.1.3</span> Simultaneous nondifferential misclassification</a></li>
  </ul></li>
  <li><a href="#selection-bias" id="toc-selection-bias" class="nav-link" data-scroll-target="#selection-bias"><span class="header-section-number">8.2</span> Selection bias</a>
  <ul class="collapse">
  <li><a href="#selection-bias-in-cohort-studies" id="toc-selection-bias-in-cohort-studies" class="nav-link" data-scroll-target="#selection-bias-in-cohort-studies"><span class="header-section-number">8.2.1</span> Selection bias in cohort studies</a></li>
  <li><a href="#selection-bias-in-case-control-studies" id="toc-selection-bias-in-case-control-studies" class="nav-link" data-scroll-target="#selection-bias-in-case-control-studies"><span class="header-section-number">8.2.2</span> Selection bias in case-control studies</a></li>
  <li><a href="#prospective-and-retrospective-studies" id="toc-prospective-and-retrospective-studies" class="nav-link" data-scroll-target="#prospective-and-retrospective-studies"><span class="header-section-number">8.2.3</span> Prospective and retrospective studies</a></li>
  <li><a href="#generalizability-and-transportability" id="toc-generalizability-and-transportability" class="nav-link" data-scroll-target="#generalizability-and-transportability"><span class="header-section-number">8.2.4</span> Generalizability and transportability</a></li>
  <li><a href="#example-berksons-bias" id="toc-example-berksons-bias" class="nav-link" data-scroll-target="#example-berksons-bias"><span class="header-section-number">8.2.5</span> Example: Berkson’s bias</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./studydesign.html">Study Design and Measures of Association</a></li><li class="breadcrumb-item"><a href="./validity.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Internal and External Validity</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Internal and External Validity</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>Validity will be evaluated in terms of two major criteria. First, and as a basic minimum, is what can be called <em>internal validity:</em> did in fact the experimental stimulus make some significant difference in this specific instance? The second criterion is that of <em>external validity,</em> <em>representativeness,</em> or <em>generalizability:</em> to what populations, settings, and variables can this effect be generalized? Both criteria are obviously important although it turns out that they are to some extent incompatible, in that the controls required for internal validity often tend to jeopardize representativeness. <span class="citation" data-cites="campbell1957factors">(<a href="references.html#ref-campbell1957factors" role="doc-biblioref">Campbell 1957</a>)</span></p>
</blockquote>
<p>In statistics, we make inferences about a population based on a sample. A study is said to have <strong>internal validity</strong> if it makes accurate measurements or inferences within the sample itself, and it is said to have <strong>external validity</strong> if these inferences accurately describe the population up to random sampling error <span class="citation" data-cites="campbell1957factors">(<a href="references.html#ref-campbell1957factors" role="doc-biblioref">Campbell 1957</a>)</span>. Both internal and external validity are best thought of as continuous, not binary. High internal validity is a prerequisite for high external validity, but there is often a tradeoff between them in practice. For simplicity, we focus on internal and external validity for descriptive epidemiology (i.e., for association and not necessarily causation).</p>
<p>So far, our discussion of 2x2 tables has assumed that the classification of exposure and disease is completely accurate and that the participants are a random sample from the population. <a href="#tbl-2x2true" class="quarto-xref">Table&nbsp;<span>8.1</span></a> shows our 2x2 table based on true exposure and disease classifications. In reality, <strong>misclassification</strong> and <strong>selection bias</strong> threaten the validity of almost all epidemiologic studies. It is critical to understand where they come from and what they do.</p>
<div id="tbl-2x2true" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-2x2true-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8.1: 2x2 table of true disease and exposure
</figcaption>
<div aria-describedby="tbl-2x2true-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;"><span class="math inline">\(D = 1\)</span></th>
<th style="text-align: center;"><span class="math inline">\(D = 0\)</span></th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(X = 1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(a\)</span></td>
<td style="text-align: center;"><span class="math inline">\(b\)</span></td>
<td style="text-align: center;"><span class="math inline">\(r_1\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(X = 0\)</span></td>
<td style="text-align: center;"><span class="math inline">\(c\)</span></td>
<td style="text-align: center;"><span class="math inline">\(d\)</span></td>
<td style="text-align: center;"><span class="math inline">\(r_0\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: center;"><span class="math inline">\(k_1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(k_0\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<section id="misclassification" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="misclassification"><span class="header-section-number">8.1</span> Misclassification</h2>
<p>Misclassification of exposure and disease threatens both the internal and external validity of an epidemiologic study. In a cohort study, we compare the exposed and unexposed groups and we have to classify disease outcomes in each group. In a case-control study, we compare cases and controls and we have to classify exposure in each group.</p>
<p><strong>Nondifferential misclassification</strong> occurs when the same classification errors affect both populations being compared. Under nondifferental misclassification, a test of the null hypothesis is still has the correct significance level but the power of the test is reduced—much like a reduction in the effective sample size <span class="citation" data-cites="bross1954misclassification rubin1956use">(<a href="references.html#ref-bross1954misclassification" role="doc-biblioref">Bross 1954</a>; <a href="references.html#ref-rubin1956use" role="doc-biblioref">Rubin, Rosenbaum, and Cobb 1956</a>)</span>. Nondifferential classification almost always causes bias toward the null, making the expected value of a given measure of association closer to the null than its true value. However, a measure of association under nondifferential misclassification can be farther away from the null than its true value due to random variation <span class="citation" data-cites="gullen1968effects sorahan1994non wacholder1995non yland2022misconceptions">(<a href="references.html#ref-gullen1968effects" role="doc-biblioref">Gullen, Bearman, and Johnson 1968</a>; <a href="references.html#ref-sorahan1994non" role="doc-biblioref">Sorahan and Gilthorpe 1994</a>; <a href="references.html#ref-wacholder1995non" role="doc-biblioref">Wacholder et al. 1995</a>; <a href="references.html#ref-yland2022misconceptions" role="doc-biblioref">Yland et al. 2022</a>)</span>.</p>
<p><strong>Differential misclassification</strong> occurs when classification errors differ between the two populations being compared. Differental misclassification can distort both the significance level and power of a hypothesis test, and it can cause bias toward the null, away from the null, or across the null. The unpredictability of the size and direction of the bias makes differential misclassification fundamentally more dangerous than nondifferential misclassification.</p>
<section id="nondifferential-misclassification-of-disease" class="level3" data-number="8.1.1">
<h3 data-number="8.1.1" class="anchored" data-anchor-id="nondifferential-misclassification-of-disease"><span class="header-section-number">8.1.1</span> Nondifferential misclassification of disease</h3>
<p>In our discussion of diagnostic tests, we let <span class="math inline">\(\Dplus\)</span> indicate <span class="math inline">\(D = 1\)</span>, <span class="math inline">\(\Dminus\)</span> indicate <span class="math inline">\(D = 0\)</span>, <span class="math inline">\(\Tplus\)</span> indicate testing positive for disease, and <span class="math inline">\(\Tminus\)</span> indicate testing negative. Let <span class="math inline">\(D^\obs\)</span> be the measured disease outcome of individuals in a cohort study where disease is detected using a diagnostic test with sensitivity <span class="math display">\[
  \sens_D
  = \Pr(\Tplus \given{} \Dplus)
  = \Pr\bigl(D^\obs = 1 \,\big|\, D = 1\bigr)
\]</span> and specificity <span class="math display">\[
  \spec_D
  = \Pr(\Tminus \given{} \Dminus)
  = \Pr\bigl(D^\obs = 0 \,\big|\, D = 0\bigr).
\]</span> We assume that <span class="math display">\[
  \sens_D
  = \Pr(\Tplus \given{} \Dplus)
  &gt; \Pr(\Tplus \,\big|\, \Dminus)
  = 1 - \spec_D,
\]</span> so individuals with disease are more likely to test positive than individuals without disease.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> This is equivalent to assuming that <span class="math inline">\(\sens_D + \spec_D &gt; 1\)</span>. We also assume that the misclassification of each participant is independent of the misclassification of all other participants. <a href="#tbl-2x2obs" class="quarto-xref">Table&nbsp;<span>8.2</span></a> shows a 2x2 table with misclassification of disease. The row sums <span class="math inline">\(r_1\)</span> and <span class="math inline">\(r_0\)</span> are the same as in <a href="#tbl-2x2true" class="quarto-xref">Table&nbsp;<span>8.1</span></a> because there is no misclassification of exposure.</p>
<div id="tbl-2x2obs" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-2x2obs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8.2: 2x2 table with misclassified disease status
</figcaption>
<div aria-describedby="tbl-2x2obs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;"><span class="math inline">\(D^\obs = 1\)</span></th>
<th style="text-align: center;"><span class="math inline">\(D^\obs = 0\)</span></th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(X = 1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(a^\obs\)</span></td>
<td style="text-align: center;"><span class="math inline">\(b^\obs\)</span></td>
<td style="text-align: center;"><span class="math inline">\(r_1\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(X = 0\)</span></td>
<td style="text-align: center;"><span class="math inline">\(c^\obs\)</span></td>
<td style="text-align: center;"><span class="math inline">\(d^\obs\)</span></td>
<td style="text-align: center;"><span class="math inline">\(r_0\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: center;"><span class="math inline">\(k_1^\obs\)</span></td>
<td style="text-align: center;"><span class="math inline">\(k_0^\obs\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Misclassification of disease is <strong>nondifferential</strong> when the sensitivity and specificity of the test are the same in all exposure groups. In other words, we have nondifferential misclassification of disease if and only if <span class="math display">\[
  \Pr\bigl(\Tplus \,\big|\, \Dplus, X = x\bigr)
  = \Pr(\Tplus \given{} \Dplus)
  = \sens_D
\]</span> and <span class="math display">\[
  \Pr\bigl(\Tminus \,\big|\, \Dminus, X = x\bigr)
  = \Pr(\Tminus \given{} \Dminus)
  = \spec_D
\]</span> for all possible values <span class="math inline">\(x\)</span> of exposure <span class="math inline">\(X\)</span>. It is critical that nondifferential misclassification is defined in terms of the sensitivity and specificity of the test, not its positive predictive value (PPV) or negative predictive value (NPV). When there is an association between exposure and disease, nondifferential misclassification of disease may produce different PPVs and NPVs in the exposed and unexposed because these predictive values depend on the prevalence of disease in addition to the sensitivity and specificity of the test <span class="citation" data-cites="newell1962errors buell1964dilution">(<a href="references.html#ref-newell1962errors" role="doc-biblioref">D. J. Newell 1962</a>; <a href="references.html#ref-buell1964dilution" role="doc-biblioref">Buell and Dunn Jr 1964</a>)</span>.</p>
<p>Under nondifferential misclassification, the probability that an exposed person tests positive for disease is <span class="math display">\[
  \begin{aligned}
    p_1^\obs
    &amp;= p_1 \sens_D + (1 - p_1) (1 - \spec_D) \\
    &amp;= (1 - \spec_D) + (\sens_D + \spec_D - 1) p_1
  \end{aligned}
\]</span> where <span class="math inline">\(p_1\)</span> is the true risk of disease in the exposed. Similarly, the probability that an unexposed person tests positive for disease is <span class="math display">\[
  p_0^\obs
  = (1 - \spec_D) + (\sens_D + \spec_D - 1) p_0
\]</span> where <span class="math inline">\(p_0\)</span> is the true risk of disease in the unexposed. The misclassified risk difference is <span id="eq-RD-obs"><span class="math display">\[
  \RD^\obs
  = p_1^\obs - p_0^\obs
  = (\sens_D + \spec_D - 1) (p_1 - p_0).
\tag{8.1}\]</span></span> Given the margins of <a href="#tbl-2x2obs" class="quarto-xref">Table&nbsp;<span>8.2</span></a>, the number <span class="math inline">\(\A^\obs\)</span> of exposed individuals who test positive for disease has a hypergeometric distribution with mean <span class="math inline">\(r_1 p_1^\obs\)</span> and the number <span class="math inline">\(\C^\obs\)</span> of unexposed people who test positive for disease has a hypergeometric distribution with mean <span class="math inline">\(r_0 p_0^\obs\)</span>. The estimated risk difference based on the misclassified data is <span class="math display">\[
  \hat{\RD}^\obs = \hat{p}_1^\obs - \hat{p}_0^\obs,
\]</span> where <span class="math inline">\(\hat{p}_1^\obs = a^\obs / r_1\)</span> and <span class="math inline">\(\hat{p}_0^\obs = c^\obs / r_0\)</span>. It is an unbiased estimate of <span class="math inline">\(\RD^\obs\)</span>.</p>
<p>When <span class="math inline">\(\sens_D &lt; 1\)</span> or <span class="math inline">\(\spec_D &lt; 1\)</span>, the misclassified risk difference <span class="math inline">\(\RD^\obs\)</span> in <a href="#eq-RD-obs" class="quarto-xref">Equation&nbsp;<span>8.1</span></a> is closer to zero than the true risk difference <span class="citation" data-cites="bross1954misclassification rubin1956use newell1963note">(<a href="references.html#ref-bross1954misclassification" role="doc-biblioref">Bross 1954</a>; <a href="references.html#ref-rubin1956use" role="doc-biblioref">Rubin, Rosenbaum, and Cobb 1956</a>; <a href="references.html#ref-newell1963note" role="doc-biblioref">D. Newell 1963</a>)</span>. The risk ratio and odds ratio are also biased toward the null under nondifferential misclassification <span class="citation" data-cites="goldberg1975effects copeland1977bias">(<a href="references.html#ref-goldberg1975effects" role="doc-biblioref">Goldberg 1975</a>; <a href="references.html#ref-copeland1977bias" role="doc-biblioref">Copeland et al. 1977</a>)</span>. This bias operates on average, not for every single estimate based on misclassified data. Even under nondifferential misclassification of disease, random variation can produce an estimate of the risk difference, risk ratio, or odds ratio that is farther from the null than the true value <span class="citation" data-cites="gullen1968effects sorahan1994non wacholder1995non yland2022misconceptions">(<a href="references.html#ref-gullen1968effects" role="doc-biblioref">Gullen, Bearman, and Johnson 1968</a>; <a href="references.html#ref-sorahan1994non" role="doc-biblioref">Sorahan and Gilthorpe 1994</a>; <a href="references.html#ref-wacholder1995non" role="doc-biblioref">Wacholder et al. 1995</a>; <a href="references.html#ref-yland2022misconceptions" role="doc-biblioref">Yland et al. 2022</a>)</span>.</p>
<p>When <span class="math inline">\(\sens_D + \spec_D &gt; 1\)</span> (as is true of any useful diagnostic or screening test), <a href="#eq-RD-obs" class="quarto-xref">Equation&nbsp;<span>8.1</span></a> implies that the null hypothesis that <span class="math inline">\(p_1^\obs = p_0^\obs\)</span> is equivalent to the null hypothesis that <span class="math inline">\(p_1 = p_0\)</span>. Both null hypotheses are equivalent to the null hypothesis that exposure and disease are independent (see <a href="studydesign.html#sec-indep-condprob" class="quarto-xref"><span>Section 7.2.1</span></a>). Therefore, a test of the null hypothesis that <span class="math inline">\(X\)</span> and <span class="math inline">\(D^\obs\)</span> are independent is also a valid test of the independence of <span class="math inline">\(X\)</span> and <span class="math inline">\(D\)</span> <span class="citation" data-cites="bross1954misclassification rubin1956use">(<a href="references.html#ref-bross1954misclassification" role="doc-biblioref">Bross 1954</a>; <a href="references.html#ref-rubin1956use" role="doc-biblioref">Rubin, Rosenbaum, and Cobb 1956</a>)</span>. The Pearson chi-squared statistic for <a href="#tbl-2x2obs" class="quarto-xref">Table&nbsp;<span>8.2</span></a> is <span id="eq-chisqPobs"><span class="math display">\[
  \chisqPobs
  = \frac{n \bigl(a^\obs d^\obs - b^\obs c^\obs\bigr)^2}{r_1 r_0 k_1^\obs k_0^\obs},
\tag{8.2}\]</span></span> and it has a <span class="math inline">\(\chi^2_1\)</span> distribution under the null hypothesis that <span class="math inline">\(p_1 = p_0\)</span>. If we set the critical value at the <span class="math inline">\(1 - \alpha\)</span> quantile of the <span class="math inline">\(\chi^2_1\)</span> distribution, the test will reject the null with probability <span class="math inline">\(\alpha\)</span> when <span class="math inline">\(p_1 = p_0\)</span> even under nondifferential misclassification of disease. A similar result holds for the hypergeometric chi-squared test, Fisher’s exact test, and other tests of independence for 2x2 tables from <a href="studydesign.html#sec-2x2independence" class="quarto-xref"><span>Section 7.2</span></a>.</p>
<p>Although nondifferential misclassification does not affect the significance level of a hypothesis test of the null hypothesis that <span class="math inline">\(p_1 = p_0\)</span>, it reduces the power of the test away from the null <span class="citation" data-cites="bross1954misclassification rubin1956use rogot1961note">(<a href="references.html#ref-bross1954misclassification" role="doc-biblioref">Bross 1954</a>; <a href="references.html#ref-rubin1956use" role="doc-biblioref">Rubin, Rosenbaum, and Cobb 1956</a>; <a href="references.html#ref-rogot1961note" role="doc-biblioref">Rogot 1961</a>)</span>. The Pearson chi-squared statistic based on the misclassified data in <a href="#tbl-2x2obs" class="quarto-xref">Table&nbsp;<span>8.2</span></a> can be rewritten <span class="math display">\[
  \chisqPobs
  = \frac{(\hat{p}_1^\obs - \hat{p}_0^\obs)^2}
    {\hat{p}^\obs (1 - \hat{p}^\obs) \Bigl(\frac{1}{r_1} + \frac{1}{r_0}\Bigr)}.
\]</span> where <span class="math inline">\(\hat{p}^\obs = k_1^\obs / n\)</span> is the misclassified estimate of the marginal risk of disease among the study participants. Let <span class="math inline">\(\varphi \in (0, 1)\)</span> be the proportion of the sample that is exposed, which we assume to be (approximately) constant as <span class="math inline">\(n \rightarrow \infty\)</span>. Let <span class="math display">\[
  K_D = \sens_D + \spec_D - 1,
\]</span> so <span class="math inline">\(K_D \in (0, 1)\)</span> whenever we have a useful but imperfect test for disease. When both <span class="math inline">\(r_1 = \varphi n\)</span> and <span class="math inline">\(r_0 = (1 - \varphi) n\)</span> are large, the numerator on the right-hand side of <a href="#eq-chisqPobs" class="quarto-xref">Equation&nbsp;<span>8.2</span></a> is approximately <span class="math display">\[
  \E(\hat{p}_1^\obs - \hat{p}_0^\obs)^2 = K_D^2 (p_1 - p_0)^2
\]</span> by the law of large numbers (LLN) and the <em>continuous mapping theorem</em>.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> Similarly, <span class="math inline">\(\hat{p}^\obs\)</span> is approximately <span class="math display">\[
  \begin{aligned}
    p^\obs
    &amp;= p\, \sens_D + (1 - p) (1 - \spec_D) \\
    &amp;= (1 - \spec_D) + K_D p,
  \end{aligned}
\]</span> where <span class="math display">\[
  p = \varphi p_1 + (1 - \varphi) p_0
\]</span> is the marginal risk of disease among the study participants. Thus, <span class="math display">\[
  \hat{p}^\obs (1 - \hat{p}^\obs)
  \approx \big(1 - \spec_D + K_D p\big) \big(1 - \sens_D + K_D (1 - p)\big).
\]</span> in large samples. It follows that <span class="math display">\[
  \chisqPobs
  \approx \frac{K_D^2 p (1 - p)}{\big(1 - \spec_D + K_D p\big) \big(1 - \sens_D + K_D (1 - p)\big)} \chisqP
\]</span> where <span class="math inline">\(\chisqP\)</span> is the Pearson chi-squared statistic based on the correctly classified data in <a href="#tbl-2x2true" class="quarto-xref">Table&nbsp;<span>8.1</span></a>. Therefore, nondifferential misclassification of disease has approximately the same effect as multiplying the sample size <span class="math inline">\(n\)</span> by the effective sample size ratio <span class="math display">\[
  \ESSR_D
  = \frac{K_D^2 p (1 - p)}{\big(1 - \spec_D + K_D p\big) \big(1 - \sens_D + K_D (1 - p)\big)}
  \leq 1
\]</span> with equality if and only if <span class="math inline">\(\sens_D = \spec_D = 1\)</span>. Thinking about nondifferential misclassification as a reduction in the effective sample size is a good way to remember both that it preserves the correct significance level under the null and that it reduces power away from the null <span class="citation" data-cites="bross1954misclassification rubin1956use">(<a href="references.html#ref-bross1954misclassification" role="doc-biblioref">Bross 1954</a>; <a href="references.html#ref-rubin1956use" role="doc-biblioref">Rubin, Rosenbaum, and Cobb 1956</a>)</span>.</p>
<p>When the prevalence or risk of disease is low, the effective sample size depends much more on the specificity of the test than on the sensitivity of the test <span class="citation" data-cites="rubin1956use">(<a href="references.html#ref-rubin1956use" role="doc-biblioref">Rubin, Rosenbaum, and Cobb 1956</a>)</span>. <a href="#fig-ESSratio" class="quarto-xref">Figure&nbsp;<span>8.1</span></a> shows the effective sample size ratio <span class="math inline">\(\ESSR_D\)</span> for three values of the marginal risk of disease in the sample (<span class="math inline">\(p\)</span>) under two different scenarios: one where <span class="math inline">\(\spec_D = 1\)</span> while sensitivity varies from zero to one and one where <span class="math inline">\(\sens_D = 1\)</span> while specificity varies from zero to one. For all three values of <span class="math inline">\(p\)</span>, <span class="math inline">\(\ESSR_D\)</span> is substantially lower in the scenario with varying specificity. This difference is greatest for <span class="math inline">\(p = 0.02\)</span> and smallest for <span class="math inline">\(p = 0.40\)</span>. If <span class="math inline">\(p = 0.5\)</span>, the two scenarios produce identical curves. If <span class="math inline">\(p &gt; 0.5\)</span>, then <span class="math inline">\(\ESSR_D\)</span> depends more on the sensitivity than the specificity of the test for disease.</p>
<div class="cell">
<div class="code-with-filename">
<details class="code-fold">
<summary>Code</summary>
<div class="code-with-filename-file">
<pre><strong>ESSratio.R</strong></pre>
</div>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Effective sample size under nondifferential misclassification</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># function that returns the effective sample size ratio</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>ess_ratio <span class="ot">&lt;-</span> <span class="cf">function</span>(sens, spec, p) {</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># returns the multiplier of the sample size to get the effective sample size</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># under nondifferential misclassification with marginal risk (or prevalence) </span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># p in the sample</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  K <span class="ot">&lt;-</span> sens <span class="sc">+</span> spec <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  Kden <span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">-</span> spec <span class="sc">+</span> K <span class="sc">*</span> p) <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> sens <span class="sc">+</span> K <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p))</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(K<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> p <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p) <span class="sc">/</span> Kden)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># data frame for ESSR with specificity = 1 and varying sensitivity</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">0.01</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.005</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.02</span>, <span class="fl">0.05</span>, <span class="fl">0.1</span>, <span class="fl">0.2</span>, <span class="fl">0.4</span>)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>pnames <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"p02"</span>, <span class="st">"p05"</span>, <span class="st">"p10"</span>, <span class="st">"p20"</span>, <span class="st">"p40"</span>)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>essr_sens <span class="ot">&lt;-</span> <span class="fu">outer</span>(s, p, <span class="cf">function</span>(s, p) <span class="fu">ess_ratio</span>(<span class="at">sens =</span> s, <span class="at">spec =</span> <span class="dv">1</span>, <span class="at">p =</span> p))</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(essr_sens) <span class="ot">&lt;-</span> pnames</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>essr_sens <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(essr_sens)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="co"># data frame for ESSR with sensitivity = 1 and varying specificity</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>essr_spec <span class="ot">&lt;-</span> <span class="fu">outer</span>(s, p, <span class="cf">function</span>(s, p) <span class="fu">ess_ratio</span>(<span class="at">sens =</span> <span class="dv">1</span>, <span class="at">spec =</span> s, <span class="at">p =</span> p))</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(essr_spec) <span class="ot">&lt;-</span> pnames</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>essr_spec <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(essr_spec)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="co"># plot</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(s, essr_spec<span class="sc">$</span>p02, <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">asp =</span> <span class="dv">1</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Sensitivity (gray) or specificity (black)"</span>,</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Effective sample size ratio"</span>)</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(s, essr_spec<span class="sc">$</span>p10, <span class="at">lty =</span> <span class="st">"dashed"</span>)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(s, essr_spec<span class="sc">$</span>p40, <span class="at">lty =</span> <span class="st">"dotdash"</span>)</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(s, essr_sens<span class="sc">$</span>p02, <span class="at">col =</span> <span class="st">"darkgray"</span>)</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(s, essr_sens<span class="sc">$</span>p10, <span class="at">col =</span> <span class="st">"darkgray"</span>, <span class="at">lty =</span> <span class="st">"dashed"</span>)</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(s, essr_sens<span class="sc">$</span>p40, <span class="at">col =</span> <span class="st">"darkgray"</span>, <span class="at">lty =</span> <span class="st">"dotdash"</span>)</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="fu">grid</span>()</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>, <span class="at">bg =</span> <span class="st">"white"</span>,</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty =</span> <span class="fu">c</span>(<span class="st">"solid"</span>, <span class="st">"dashed"</span>, <span class="st">"dotdash"</span>),</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"p = 0.02"</span>, <span class="st">"p = 0.10"</span>, <span class="st">"p = 0.40"</span>))</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fl">0.48</span>, <span class="fl">0.52</span>, <span class="at">srt =</span> <span class="dv">45</span>, <span class="at">col =</span> <span class="st">"darkgray"</span>,</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>     <span class="st">"Specificity = 1 with varying sensitivity"</span>)</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fl">0.68</span>, <span class="fl">0.32</span>, <span class="at">srt =</span> <span class="dv">45</span>, <span class="st">"Sensitivity = 1 with varying specificity"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell-output-display">
<div id="fig-ESSratio" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ESSratio-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="validity_files/figure-html/fig-ESSratio-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;8.1: The effective sample size ratio \ESSR_D as a function of \sens_D when \spec_D = 1 (gray lines) and as a function of \spec_D when \sens_D = 1 (black lines)."><img src="validity_files/figure-html/fig-ESSratio-1.png" class="img-fluid figure-img" width="672"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ESSratio-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.1: The effective sample size ratio <span class="math inline">\(\ESSR_D\)</span> as a function of <span class="math inline">\(\sens_D\)</span> when <span class="math inline">\(\spec_D = 1\)</span> (gray lines) and as a function of <span class="math inline">\(\spec_D\)</span> when <span class="math inline">\(\sens_D = 1\)</span> (black lines).
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="nondifferential-misclassification-of-exposure" class="level3" data-number="8.1.2">
<h3 data-number="8.1.2" class="anchored" data-anchor-id="nondifferential-misclassification-of-exposure"><span class="header-section-number">8.1.2</span> Nondifferential misclassification of exposure</h3>
<p>Nondifferential misclassification of exposure has effects similar to those of nondifferential misclassification of disease. Although we usually discuss sensitivity and specificity in the context of a test for disease, the same ideas can be applied to a test or measurement used to determine exposure status. For simplicity, we will focus on a binary exposure <span class="math inline">\(X\)</span> with <span class="math inline">\(\Xplus\)</span> indicating <span class="math inline">\(X = 1\)</span> and <span class="math inline">\(\Xminus\)</span> indicating <span class="math inline">\(X = 0\)</span>.</p>
<p>Let <span class="math inline">\(\Xobs\)</span> be the measured disease outcome of individuals in a case-control study when we classify exposure using a test <span class="math inline">\(T_X\)</span> that has sensitivity <span class="math display">\[
  \sens_X
  = \Pr\bigl(\Tplus_X \,\big|\,\Xplus\bigr)
  = \Pr\bigl(\Xobs = 1 \,\big|\, X = 1\bigr)
\]</span> and specificity <span class="math display">\[
  \spec_X
  = \Pr\bigl(\Tminus_X \,\big|\, \Xminus\bigr)
  = \Pr\bigl(\Xobs = 0 \,\big|\, X = 0\bigr).
\]</span> We assume that <span class="math inline">\(\sens_X &gt; 1 - \spec_X\)</span>, so exposed individuals are more likely to test positive for exposure than unexposed individuals. This is equivalent to assuming <span class="math inline">\(\sens_X + \spec_X &gt; 1\)</span>.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> We also assume that the misclassification of each participant is independent of the misclassification of all other participants. <a href="#tbl-2x2obsX" class="quarto-xref">Table&nbsp;<span>8.3</span></a> shows a 2x2 table with exposure misclassification. The column sums <span class="math inline">\(k_1\)</span> and <span class="math inline">\(k_0\)</span> are the same in both tables because there is no misclassification of disease status.</p>
<div id="tbl-2x2obsX" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-2x2obsX-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8.3: 2x2 table with misclassified exposure
</figcaption>
<div aria-describedby="tbl-2x2obsX-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;"><span class="math inline">\(D = 1\)</span></th>
<th style="text-align: center;"><span class="math inline">\(D = 0\)</span></th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(X^\obs = 1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(a^\obs\)</span></td>
<td style="text-align: center;"><span class="math inline">\(b^\obs\)</span></td>
<td style="text-align: center;"><span class="math inline">\(r_1^\obs\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(X^\obs = 0\)</span></td>
<td style="text-align: center;"><span class="math inline">\(c^\obs\)</span></td>
<td style="text-align: center;"><span class="math inline">\(d^\obs\)</span></td>
<td style="text-align: center;"><span class="math inline">\(r_0^\obs\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: center;"><span class="math inline">\(k_1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(k_0\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The misclassification of exposure is nondifferential when the sensitivity and specificity of the exposure test are the same in cases and controls. In other words, we need <span class="math display">\[
  \Pr\bigl(\Tplus_X \,\big|\, \Xplus, D = d\bigr)
  = \Pr\bigl(\Tplus_X \,\big|\, \Xplus\bigr)
\]</span> and <span class="math display">\[
  \Pr\bigl(\Tminus_X \,\big|\, \Xminus, D = d\bigr)
  = \Pr\bigl(\Tminus_X \,\big|\, \Xminus\bigr)
\]</span> for all possible values <span class="math inline">\(d\)</span> of disease status <span class="math inline">\(D\)</span>. As with disease, it is critical that nondifferential misclassification of exposure is defined through the sensitivity and specificity of the test for exposure. When there is an association between exposure and disease, nondifferential misclassification can produce a PPV and NPV that differ between cases and controls because these predictive values depend on the prevalence of exposure in addition to the sensitivity and specificity of the test <span class="citation" data-cites="newell1962errors buell1964dilution">(<a href="references.html#ref-newell1962errors" role="doc-biblioref">D. J. Newell 1962</a>; <a href="references.html#ref-buell1964dilution" role="doc-biblioref">Buell and Dunn Jr 1964</a>)</span>.</p>
<p>Under nondifferential misclassification, the probability that a case tests positive for exposure is <span class="math display">\[
    \pi_1^\obs
    = (1 - \spec_X) + (\sens_X + \spec_X - 1) \pi_1
\]</span> where <span class="math inline">\(\pi_1\)</span> is the true prevalence of exposure among cases. Similarly, the probability that a control tests positive for exposure is <span class="math display">\[
  \pi_0^\obs
  = (1 - \spec_X) + (\sens_X + \spec_X - 1) p_0
\]</span> where <span class="math inline">\(\pi_0\)</span> is the true prevalence of exposure in controls. The misclassified difference in exposure prevalences is <span class="math display">\[
  \pi_1^\obs - \pi_0^\obs
  = (\sens_X + \spec_X - 1) (\pi_1 - \pi_0).
\]</span> When <span class="math inline">\(\sens_X + \spec_X &gt; 1\)</span> (as is true of any useful test for exposure), the null hypothesis that <span class="math inline">\(\pi_1^\obs = \pi_0^\obs\)</span> is equivalent to the null hypothesis that <span class="math inline">\(\pi_1 = \pi_0\)</span>, which is equivalent to the null hypothesis that exposure and disease are independent (see <a href="studydesign.html#sec-indep-condprob" class="quarto-xref"><span>Section 7.2.1</span></a>). Therefore, any test of the independence of <span class="math inline">\(X^\obs\)</span> and <span class="math inline">\(D\)</span> has the correct significance level under the null hypothesis that <span class="math inline">\(X\)</span> and <span class="math inline">\(D\)</span> are independent <span class="citation" data-cites="bross1954misclassification">(<a href="references.html#ref-bross1954misclassification" role="doc-biblioref">Bross 1954</a>)</span>.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<p>Like nondifferential misclassification of disease, nondifferential misclassification of exposure reduces the power of the hypothesis test that exposure and disease are independent <span class="citation" data-cites="bross1954misclassification rubin1956use rogot1961note">(<a href="references.html#ref-bross1954misclassification" role="doc-biblioref">Bross 1954</a>; <a href="references.html#ref-rubin1956use" role="doc-biblioref">Rubin, Rosenbaum, and Cobb 1956</a>; <a href="references.html#ref-rogot1961note" role="doc-biblioref">Rogot 1961</a>)</span>. The maximum likelihood estimates <span class="math inline">\(\hat{\pi}_1^\obs = a^\obs / k_1\)</span> and <span class="math inline">\(\hat{\pi}_0^\obs = b^\obs / k_0\)</span> are unbiased. The Pearson chi-squared statistic based on the misclassified data in Table~<a href="#tab:2by2obsX" data-reference-type="ref" data-reference="tab:2by2obsX">[tab:2by2obsX]</a> can be rewritten <span id="eq-chisqPobsX"><span class="math display">\[
  \chisqPobs
  = \frac{(\hat{\pi}_1^\obs - \hat{\pi}_0^\obs)^2}
    {\hat{\pi}^\obs (1 - \hat{\pi}^\obs) \Bigl(\frac{1}{k_1} + \frac{1}{k_0}\Bigr)}.
\tag{8.3}\]</span></span> where <span class="math inline">\(\hat{\pi}^\obs = k_1^\obs / n\)</span> is the misclassified estimate of the marginal prevalence of exposure among the study participants. Let <span class="math inline">\(\varphi_X\)</span> be the proportion of the sample that consists of cases, and let <span class="math inline">\(K_X = \sens_X + \spec_X - 1\)</span>, so <span class="math inline">\(K_X \in (0, 1)\)</span> whenever we have a useful but imperfect test for exposure. When both <span class="math inline">\(k_1 = \varphi_X n\)</span> and <span class="math inline">\(k_0 = (1 - \varphi_X) n\)</span> are large, the numerator on the right-hand side of <a href="#eq-chisqPobsX" class="quarto-xref">Equation&nbsp;<span>8.3</span></a> is approximately <span class="math display">\[
  \E(\hat{\pi}_1^\obs - \hat{\pi}_0^\obs)^2
  = K_X^2 (\pi_1 - \pi_0)^2,
\]</span> and <span class="math display">\[
    \hat{\pi}^\obs
    \approx \E(\hat{\pi}^\obs)
    = (1 - \spec_X) + K_X \pi
\]</span> where <span class="math display">\[
  \pi = \varphi_X \pi_1 + (1 - \varphi_X) \pi_0
\]</span> is the marginal prevalence of exposure among the study participants, In large samples, <span class="math display">\[
    \hat{\pi}^\obs (1 - \hat{\pi}^\obs)
    \approx \big(1 - \spec_X + K_X \pi\big) \big(1 - \sens_X + K_X (1 - \pi)\big).
\]</span> For hypothesis testing, nondifferential misclassification of exposure has approximately the same effect as multiplying the sample size <span class="math inline">\(n\)</span> by the effective sample size ratio <span class="math display">\[
  \ESSR_X
  = \frac{K_X^2 \pi (1 - \pi)}{\big(1 - \spec_X + K_X \pi\big) \big(1 - \sens_X + K_X (1 - \pi)\big)}
  \leq 1
\]</span> with equality if and only if <span class="math inline">\(\sens_X = \spec_X = 1\)</span>. Just like nondifferential misclassification of disease, nondifferential misclassification of exposure acts like reduction in the effective sample size. It preserves the significance level under the null, but it reduces the power of the test away from the null. A similar reduction in power occurs when more complex exposures (such as dietary intakes) are measured with error, requiring larger sample sizes to achieve a given power <span class="citation" data-cites="freedman1990impact">(<a href="references.html#ref-freedman1990impact" role="doc-biblioref">Freedman, Schatzkin, and Wax 1990</a>)</span>.</p>
<p>The curves in <a href="#fig-ESSratio" class="quarto-xref">Figure&nbsp;<span>8.1</span></a> are the same if we replace the marginal risk of disease <span class="math inline">\(p\)</span> with the marginal prevalence of exposure <span class="math inline">\(\pi\)</span>. The effective sample size ratio <span class="math inline">\(\ESSR_X\)</span> depends on the specificity more than the sensitivity when <span class="math inline">\(\pi &lt; 0.5\)</span>, and it depends on the sensitivity more than the specificity when <span class="math inline">\(\pi &gt; 0.5\)</span>. While diseases typically (and fortunately) have low risks, exposures can have both low and high prevalences.</p>
<p>When there are more than two levels of exposure, nondifferential misclassification does not always bias a measure of association toward the null for all exposure categories <span class="citation" data-cites="walker1988analysis dosemeci1990does verkerk1992non correa1995bias">(<a href="references.html#ref-walker1988analysis" role="doc-biblioref">Walker, Velema, and Robins 1988</a>; <a href="references.html#ref-dosemeci1990does" role="doc-biblioref">Dosemeci, Wacholder, and Lubin 1990</a>; <a href="references.html#ref-verkerk1992non" role="doc-biblioref">Verkerk and Buitendijk 1992</a>; <a href="references.html#ref-correa1995bias" role="doc-biblioref">Correa-Villaseñor et al. 1995</a>)</span>. Misclassification causes the risks of disease in different exposure categories to get closer to each other on average. Without loss of generality, suppose that higher exposure is associated with a higher risk of disease. Misclassification of high-exposure individuals to lower-exposure categories can increase the apparent risk of disease in these categories, and misclassification of low-exposure individuals into higher-exposure categories can decrease the apparent risk of disease in these categories. The risk in the highest-exposure category can only go down on average due to misclassification, and the risk in the lowest-exposure category can only go up on average. In both cases, this results in bias toward the null—and these are the only possible cases for a binary exposure. The risk in an intermediate-exposure category can go up or down on average, so some measures of association can be biased away from the null. Despite this exception, bias toward the null remains the most likely outcome of nondifferential misclassification of exposure <span class="citation" data-cites="dosemeci1990does correa1995bias">(<a href="references.html#ref-dosemeci1990does" role="doc-biblioref">Dosemeci, Wacholder, and Lubin 1990</a>; <a href="references.html#ref-correa1995bias" role="doc-biblioref">Correa-Villaseñor et al. 1995</a>)</span>. However, random variation can produce point estimates closer to, farther from, or across the null compared to the true value of a measure of association.</p>
</section>
<section id="simultaneous-nondifferential-misclassification" class="level3" data-number="8.1.3">
<h3 data-number="8.1.3" class="anchored" data-anchor-id="simultaneous-nondifferential-misclassification"><span class="header-section-number">8.1.3</span> Simultaneous nondifferential misclassification</h3>
<p>Although we discussed nondifferential misclassification of disease in the context of a cohort study and nondifferential misclassification of exposure in the context of a case-control study, simultaneously misclassification of <span class="math inline">\(X\)</span> and <span class="math inline">\(D\)</span> can occur in any epidemiologic study. <a href="#tbl-2x2obsXD" class="quarto-xref">Table&nbsp;<span>8.4</span></a> shows a 2x2 table with <span class="math inline">\(X\)</span> and <span class="math inline">\(D\)</span> both misclassified. The row totals are affected by misclassification of <span class="math inline">\(X\)</span>, and the column totals are affected by misclassification of <span class="math inline">\(D\)</span>. Only the total sample size <span class="math inline">\(n\)</span> is unaffected.</p>
<div id="tbl-2x2obsXD" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-2x2obsXD-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8.4: 2x2 table for a study with misclassified exposure and disease
</figcaption>
<div aria-describedby="tbl-2x2obsXD-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;"><span class="math inline">\(D^\obs = 1\)</span></th>
<th style="text-align: center;"><span class="math inline">\(D^\obs = 0\)</span></th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(X^\obs = 1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(a^\obs\)</span></td>
<td style="text-align: center;"><span class="math inline">\(b^\obs\)</span></td>
<td style="text-align: center;"><span class="math inline">\(r_1^\obs\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(X^\obs = 0\)</span></td>
<td style="text-align: center;"><span class="math inline">\(c^\obs\)</span></td>
<td style="text-align: center;"><span class="math inline">\(d^\obs\)</span></td>
<td style="text-align: center;"><span class="math inline">\(r_0^\obs\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: center;"><span class="math inline">\(k_1^\obs\)</span></td>
<td style="text-align: center;"><span class="math inline">\(k_0^\obs\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The effects of nondifferential misclassification of both <span class="math inline">\(X\)</span> and <span class="math inline">\(D\)</span> can be derived by imagining that we misclassify one first and then the other. Here, we will consider misclassifying <span class="math inline">\(X\)</span> and then <span class="math inline">\(D\)</span>. When we misclassify <span class="math inline">\(X\)</span>, we have the equivalent null hypotheses <span class="math display">\[
  X \indep D \iff X^\obs \indep D.
\]</span> where the symbol <span class="math inline">\(\indep\)</span> indicates independence <span class="citation" data-cites="dawid1979conditional">(<a href="references.html#ref-dawid1979conditional" role="doc-biblioref">Dawid 1979</a>)</span>. When we misclassify <span class="math inline">\(D\)</span> in addition to <span class="math inline">\(X\)</span>, we have the equivalent null hypotheses <span class="math display">\[
  X^\obs \indep D \iff X^\obs \indep D^\obs.
\]</span> Therefore, <span class="math display">\[
  X \indep D \iff X^\obs \indep D^\obs
\]</span> so a test of the null hypothesis that <span class="math inline">\(X\)</span> and <span class="math inline">\(D\)</span> are independent based on the misclassified data in <a href="#tbl-2x2obsXD" class="quarto-xref">Table&nbsp;<span>8.4</span></a> has the correct significance level (as long as <span class="math inline">\(\sens_X + \spec_X &gt; 1\)</span> and <span class="math inline">\(\sens_D + \spec_D &gt; 1\)</span>). However, the power of the test is reduced when we misclassify <span class="math inline">\(X\)</span> and reduced again when we misclassify <span class="math inline">\(D\)</span>. Simultaneous misclassification of <span class="math inline">\(X\)</span> and <span class="math inline">\(D\)</span> has approximately the same effect as multiplying the sample size by <span class="math display">\[
  \ESSR_X \ESSR_D \leq 1
\]</span> with equality if and only if <span class="math inline">\(\sens_X = \spec_X = 1\)</span> and <span class="math inline">\(\sens_D = \spec_D = 1\)</span>.</p>
</section>
</section>
<section id="selection-bias" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="selection-bias"><span class="header-section-number">8.2</span> Selection bias</h2>
<p>Participants in an epidemiologic study can be selected according to exposure (in a cohort study) or according to disease (in a case-control study), but they cannot be selected according to both. In a cohort study, selection must be conditionally independent of disease given exposure so that risks of disease are estimated accurately in all exposure groups. In a case-control study, selection must be conditionally independent of exposure given disease, so the prevalence of exposure is measured accurately among both cases and controls.. Selection according to exposure and disease simultaneously leads to <strong>selection bias</strong>, which is a threat to the external validity of a study.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> A study with uncontrolled selection bias is neither generalizable nor transportable.</p>
<section id="selection-bias-in-cohort-studies" class="level3" data-number="8.2.1">
<h3 data-number="8.2.1" class="anchored" data-anchor-id="selection-bias-in-cohort-studies"><span class="header-section-number">8.2.1</span> Selection bias in cohort studies</h3>
<p>In a cohort study, selection bias leads to biased estimates of the risks of disease in exposure groups. Let <span class="math inline">\(S\)</span> indicate selection into the study, so <span class="math inline">\(S_i = 1\)</span> if individual <span class="math inline">\(i\)</span> is selected into the study and <span class="math inline">\(S_i = 0\)</span> otherwise. When only <span class="math inline">\(X\)</span> and <span class="math inline">\(D\)</span> are measured, there is no selection bias in a cohort study if and only if the conditional probability of disease given exposure in sampled individuals equals that in the population: <span id="eq-SBcohort"><span class="math display">\[
  \Pr(D = 1 \given{} X = x, S = 1)
  = \Pr(D = 1 \given{} X = x)
\tag{8.4}\]</span></span> for both <span class="math inline">\(x = 1\)</span> and <span class="math inline">\(x = 0\)</span>. By the definition of conditional probability, <span class="math display">\[
  \Pr(D = 1 \given{} X = x, S = 1)
  = \frac{\Pr(D = 1, S = 1 \given{} X = x)}{\Pr(S = 1 \given{} X = x)}.
\]</span> Multiplying both sides of <a href="#eq-SBcohort" class="quarto-xref">Equation&nbsp;<span>8.4</span></a> by <span class="math inline">\(\Pr(S = 1 \given{} X = x)\)</span> show that there is no selection bias in a cohort study if and only if <span id="eq-SBcohort2"><span class="math display">\[
  \Pr(D = 1, S = 1 \given{} X = x)
  = \Pr(D = 1 \given{} X = x) \Pr(S = 1 \given{} X = x),
\tag{8.5}\]</span></span> which means that <span class="math inline">\(D\)</span> and <span class="math inline">\(S\)</span> are conditionally independent given <span class="math inline">\(X\)</span>. This condition can be relaxed somewhat if additional covariates are measured. In that case, we only need <span class="math inline">\(D\)</span> and <span class="math inline">\(S\)</span> to be conditionally independent given the measured covariates.</p>
</section>
<section id="selection-bias-in-case-control-studies" class="level3" data-number="8.2.2">
<h3 data-number="8.2.2" class="anchored" data-anchor-id="selection-bias-in-case-control-studies"><span class="header-section-number">8.2.2</span> Selection bias in case-control studies</h3>
<p>In a case-control study, selection bias leads to biased estimates of exposure prevalences in cases and controls. When only <span class="math inline">\(X\)</span> and <span class="math inline">\(D\)</span> are measured, there is no selection bias in a case-control study if and only if the conditional probability of exposure given disease in sampled individuals equals that in the underlying population: <span id="eq-SBcc"><span class="math display">\[
  \Pr(X = 1 \given{} D = d)
  = \Pr(X = 1 \given{} D = d, S = 1)
\tag{8.6}\]</span></span> for <span class="math inline">\(d = 1\)</span> and <span class="math inline">\(d = 0\)</span>. By the same argument used for the cohort study, there is no selection bias in a case-control study if and only if <span class="math display">\[
  \Pr(X = 1, S = 1 \given{} D = d)
  = \Pr(X = 1 \given{} D = d) \Pr(S = 1 \given{} D = d),
\]</span> which means that <span class="math inline">\(X\)</span> and <span class="math inline">\(S\)</span> are conditionally independent given <span class="math inline">\(D\)</span>. As with selection bias in a cohort study, this condition can be relaxed if additional covariates are measured.</p>
</section>
<section id="prospective-and-retrospective-studies" class="level3" data-number="8.2.3">
<h3 data-number="8.2.3" class="anchored" data-anchor-id="prospective-and-retrospective-studies"><span class="header-section-number">8.2.3</span> Prospective and retrospective studies</h3>
<p>A <strong>prospective study</strong> is one in which exposure information is collected and recorded prior to disease onset. A <strong>retrospective study</strong> is one in which exposure information is collected after the onset of disease. Traditionally, cohort studies were called “prospective studies” and case-control studies were called “retrospective studies”. While this classification is often accurate, it is possible for either design to be prospective or retrospective <span class="citation" data-cites="rothman2008modern">(<a href="references.html#ref-rothman2008modern" role="doc-biblioref">Rothman, Greenland, and Lash 2008</a>)</span>.</p>
<p>Because selection into a retrospective study occurs after disease onset and relevant exposures occur prior to disease onset, retrospective studies are more susceptible to selection bias than prospective studies. Because knowledge of disease occurrence can affect recall or measurement of exposure, retrospective studies are also more susceptible to differential misclassification.</p>
</section>
<section id="generalizability-and-transportability" class="level3" data-number="8.2.4">
<h3 data-number="8.2.4" class="anchored" data-anchor-id="generalizability-and-transportability"><span class="header-section-number">8.2.4</span> Generalizability and transportability</h3>
<p>To discuss sources of bias in epidemiologic studies, we will use terminology adapted from <span class="citation" data-cites="dahabreh2019extending">Dahabreh and Hernán (<a href="references.html#ref-dahabreh2019extending" role="doc-biblioref">2019</a>)</span> and illustrated in <a href="#fig-populations" class="quarto-xref">Figure&nbsp;<span>8.2</span></a>. These terms are meant to be consistent with the Consolidated Standards of Reporting Trials (CONSORT) statement <span class="citation" data-cites="moher2001consort altman2001revised">(<a href="references.html#ref-moher2001consort" role="doc-biblioref">Moher et al. 2001</a>; <a href="references.html#ref-altman2001revised" role="doc-biblioref">Altman et al. 2001</a>)</span> as well as the Strengthening the Reporting of Observational Studies in Epidemiology (STROBE) statement <span class="citation" data-cites="von2007strengthening vandenbroucke2007strengthening">(<a href="references.html#ref-von2007strengthening" role="doc-biblioref">Elm et al. 2007</a>; <a href="references.html#ref-vandenbroucke2007strengthening" role="doc-biblioref">Vandenbroucke et al. 2007</a>)</span>. The <strong>eligible population</strong> is the population of individuals who meet the eligibility criteria for a study—whether or not they are invited to participate or willing to participate. Individuals within the eligible population who are invited to participate are the <strong>invited population</strong>, and those within the invited population who enroll in the study are the <strong>study sample</strong>.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> Members of the study sample are called <strong>participants</strong>. Inferences based on data from the study sample are applied to a <strong>target population</strong> that could be the eligible population or a population that includes individuals outside the eligible population.</p>
<p>A study that makes valid inferences for the eligible population has <strong>generalizability</strong>, and a study that makes valid inferences for a larger or different target population has <strong>transportability</strong> to that population. Generalizability and transportability live along a spectrum of external validity. Generalizability is typically a prerequisite for transportability, and a generalizable study can be transportable to some target populations but not to others. Qualitative insights (e.g., smoking causes lung cancer) might be generalizable or transportable even when the estimated risks of disease or prevalences of exposure are not. The best way to ensure that the results of a study are widely applicable is to make the eligible population as inclusive as possible within ethical and logistical constraints <span class="citation" data-cites="nasem2022improving">(<a href="references.html#ref-nasem2022improving" role="doc-biblioref">Bibbins-Domingo and Helman 2022</a>)</span>.</p>
<div id="fig-populations" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-populations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="./images/populations.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;8.2: Schematic illustration of the relationship between the study sample, the eligible population, and a target population. A target population can contain all, part, or none of the eligible population."><img src="./images/populations.png" class="img-fluid figure-img" style="width:70.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-populations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.2: Schematic illustration of the relationship between the study sample, the eligible population, and a target population. A target population can contain all, part, or none of the eligible population.
</figcaption>
</figure>
</div>
</section>
<section id="example-berksons-bias" class="level3" data-number="8.2.5">
<h3 data-number="8.2.5" class="anchored" data-anchor-id="example-berksons-bias"><span class="header-section-number">8.2.5</span> Example: Berkson’s bias</h3>
<p><span class="citation" data-cites="berkson1946limitations">Berkson (<a href="references.html#ref-berkson1946limitations" role="doc-biblioref">1946</a>)</span> discussed a hypothetical case-control study to test whether cholecystitis (i.e., gallbladder inflammation) is associated with diabetes. The cases are patients who come to the clinic for diabetes treatment. The controls are nondiabetic patients who come to the clinic to get eyeglasses to correct refractive errors, a diagnosis considered to be independent of cholecystitis based on existing knowledge of human biology. The overall population has 10,000,000 individuals. The prevalence of diabetes is 1%, the prevalence of refractive errors is 10%, and the prevalence of cholecystitis is 3%. All three conditions are assumed to occur independently.</p>
<p><a href="#tbl-Berkson-pop" class="quarto-xref">Table&nbsp;<span>8.5</span></a> shows the distribution of cholecystitis among individuals with diabetes and individuals with refractive errors. Eligible cases are individuals with diabetes, and eligible controls are individuals with refractive errors but no diabetes. The prevalence of cholecystitis is <span class="math inline">\(3\%\)</span> in both groups, so <span class="math inline">\(\pi_1 = \pi_0 = 0.03\)</span>. It follows that the Pearson chi-squared statistic <span class="math inline">\(\chisqP = 0\)</span> in the 2x2 table for the eligible population.</p>
<div id="tbl-Berkson-pop" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Berkson-pop-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8.5: Cholecystitis among eligible cases and controls in <span class="citation" data-cites="berkson1946limitations">Berkson (<a href="references.html#ref-berkson1946limitations" role="doc-biblioref">1946</a>)</span>
</figcaption>
<div aria-describedby="tbl-Berkson-pop-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Eligible cases</th>
<th style="text-align: right;">Eligible controls</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cholecystitis</td>
<td style="text-align: right;">3,000</td>
<td style="text-align: right;">29,700</td>
<td style="text-align: right;">32,700</td>
</tr>
<tr class="even">
<td style="text-align: left;">No cholecystitis</td>
<td style="text-align: right;">97,000</td>
<td style="text-align: right;">960,300</td>
<td style="text-align: right;">1,057,300</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">100,000</td>
<td style="text-align: right;">990,000</td>
<td style="text-align: right;">1,090,000</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The study sample consists of patients who visit the clinic for diabetes or refractive errors. Each diagnosis comes with a probability of visiting the clinic in the relevant time period. In one version of the example, diabetes patients visit the clinic with probability <span class="math inline">\(0.05\)</span>, refractive error patients visit with probability <span class="math inline">\(0.20\)</span>, and cholecystitis patients visit with probability <span class="math inline">\(0.15\)</span>. For patients with multiple conditions, “we shall say that these selective probabilities operate independently, as though a person who had two diseases were like [conjoined] twins, each one of whom had one disease, so that the probability of the twins’ coming to the hospital is the probability of either one getting there, but the presence of one disease does not affect the other in any way” <span class="citation" data-cites="berkson1946limitations">(<a href="references.html#ref-berkson1946limitations" role="doc-biblioref">Berkson 1946</a>)</span>. For example, a patient with both diabetes and refractive error visits the clinic with probability <span class="math inline">\(1 - (1 - 0.05) (1 - 0.20) = 0.24\)</span>. <a href="#tbl-Berkson-selection" class="quarto-xref">Table&nbsp;<span>8.6</span></a> shows the numbers of individuals in the population and among clinic visitors at each combination of cholecystitis, diabetes, and refractive errors.</p>
<div id="tbl-Berkson-selection" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Berkson-selection-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8.6: Combinations of cholecystitis (C), diabetes (D), and refractive errors (R) in <span class="citation" data-cites="berkson1946limitations">Berkson (<a href="references.html#ref-berkson1946limitations" role="doc-biblioref">1946</a>)</span>.
</figcaption>
<div aria-describedby="tbl-Berkson-selection-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Condition</th>
<th style="text-align: right;">Population</th>
<th style="text-align: left;">Selection probability</th>
<th style="text-align: right;">Clinic visitors</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">None</td>
<td style="text-align: right;">8,642,700</td>
<td style="text-align: left;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">C only</td>
<td style="text-align: right;">267,300</td>
<td style="text-align: left;">0.15</td>
<td style="text-align: right;">40,095</td>
</tr>
<tr class="odd">
<td style="text-align: left;">D only</td>
<td style="text-align: right;">87,300</td>
<td style="text-align: left;">0.05</td>
<td style="text-align: right;">4,365</td>
</tr>
<tr class="even">
<td style="text-align: left;">R only</td>
<td style="text-align: right;">960,300</td>
<td style="text-align: left;">0.20</td>
<td style="text-align: right;">192,060</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C and D</td>
<td style="text-align: right;">2,700</td>
<td style="text-align: left;">0.1925</td>
<td style="text-align: right;">520</td>
</tr>
<tr class="even">
<td style="text-align: left;">C and R</td>
<td style="text-align: right;">29,700</td>
<td style="text-align: left;">0.32</td>
<td style="text-align: right;">9,504</td>
</tr>
<tr class="odd">
<td style="text-align: left;">D and R</td>
<td style="text-align: right;">9,700</td>
<td style="text-align: left;">0.24</td>
<td style="text-align: right;">2,328</td>
</tr>
<tr class="even">
<td style="text-align: left;">C, D, and R</td>
<td style="text-align: right;">300</td>
<td style="text-align: left;">0.354</td>
<td style="text-align: right;">106</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">10,000,000</td>
<td style="text-align: left;">0.0249</td>
<td style="text-align: right;">248,978</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><a href="#tbl-Berkson-sample" class="quarto-xref">Table&nbsp;<span>8.7</span></a> shows the 2x2 table for the study sample. The cases with cholecystitis include the 520 individuals with diabetes and cholecystitis only and the 106 individuals with all three conditions. The cases without cholecystitis include the 4,365 individuals with diabetes only and the 2,328 individuals with diabetes and refractive errors only. In this table, we have <span class="math display">\[
  \chisqP = \frac{208{,}883 (626 \times 192{,}060 - 6{,}693 \times 192{,}060)^2}
    {10{,}130 \times 198{,}753 \times 7{,}319 \times 201{,}564}
  \approx 225.447.
\]</span> The p-value is <span class="math inline">\(5.9 \times 10^{-51}\)</span>.</p>
<div id="tbl-Berkson-sample" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Berkson-sample-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8.7: Cholecystitis among cases and controls in <span class="citation" data-cites="berkson1946limitations">Berkson (<a href="references.html#ref-berkson1946limitations" role="doc-biblioref">1946</a>)</span>
</figcaption>
<div aria-describedby="tbl-Berkson-sample-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Cases</th>
<th style="text-align: right;">Controls</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cholecystitis</td>
<td style="text-align: right;">520 + 106 = 626</td>
<td style="text-align: right;">9,504</td>
<td style="text-align: right;">10,130</td>
</tr>
<tr class="even">
<td style="text-align: left;">No cholecystitis</td>
<td style="text-align: right;">4,365 + 2,328 = 6,693</td>
<td style="text-align: right;">192,060</td>
<td style="text-align: right;">198,753</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">7,319</td>
<td style="text-align: right;">201,564</td>
<td style="text-align: right;">208,883</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>If we ignored selection bias, we would conclude that there is almost certainly an association between cholecystitis and diabetes in the eligible population. The example is constructed with no such association. Because the study sample included only clinic visitors and individuals with multiple conditions (including cholecystitis) were more likely to visit the clinic, selection and exposure (cholecystitis) are not conditionally independent given disease in this example.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" aria-current="page">R</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>Berkson.R</strong></pre>
</div>
<div class="sourceCode" id="cb2" data-filename="Berkson.R"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Berkson (1946) example of selection bias</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Pearson chi-squared test for the eligible population (X and D independent)</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>poptab <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">3000</span>, <span class="dv">97000</span>, <span class="dv">29700</span>, <span class="dv">960300</span>), <span class="at">nrow =</span> <span class="dv">2</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(poptab, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Fisher's exact test (with confidence limits for odds ratio)</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(poptab)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Pearson chi-squared test for the study sample (X and D not independent)</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>sampletab <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">626</span>, <span class="dv">6693</span>, <span class="dv">9504</span>, <span class="dv">192060</span>), <span class="at">nrow =</span> <span class="dv">2</span>)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(sampletab, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Fisher's exact test (with confidence limits for odds ratio)</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(sampletab)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-altman2001revised" class="csl-entry" role="listitem">
Altman, Douglas G, Kenneth F Schulz, David Moher, Matthias Egger, Frank Davidoff, Diana Elbourne, Peter C Gøtzsche, Thomas Lang, and CONSORT Group. 2001. <span>“The Revised <span>CONSORT</span> Statement for Reporting Randomized Trials: Explanation and Elaboration.”</span> <em>Annals of Internal Medicine</em> 134 (8): 663–94.
</div>
<div id="ref-berkson1946limitations" class="csl-entry" role="listitem">
Berkson, Joseph. 1946. <span>“Limitations of the Application of Fourfold Table Analysis to Hospital Data.”</span> <em>Biometrics Bulletin</em> 2 (3): 47–53.
</div>
<div id="ref-nasem2022improving" class="csl-entry" role="listitem">
Bibbins-Domingo, Kirsten, and Alex Helman, eds. 2022. <em>Improving Representation in Clinical Trials and Research: Building Research Equity for Women and Underrepresented Groups</em>. National Academies of Sciences, Engineering,; Medicine (National Academies Press).
</div>
<div id="ref-bross1954misclassification" class="csl-entry" role="listitem">
Bross, Irwin. 1954. <span>“Misclassification in 2 x 2 Tables.”</span> <em>Biometrics</em> 10 (4): 478–86.
</div>
<div id="ref-buell1964dilution" class="csl-entry" role="listitem">
Buell, Philip, and John E Dunn Jr. 1964. <span>“The Dilution Effect of Misclassification.”</span> <em>American Journal of Public Health</em> 54 (4): 598–602.
</div>
<div id="ref-campbell1957factors" class="csl-entry" role="listitem">
Campbell, Donald T. 1957. <span>“Factors Relevant to the Validity of Experiments in Social Settings.”</span> <em>Psychological Bulletin</em> 54 (4): 297.
</div>
<div id="ref-chung2000course" class="csl-entry" role="listitem">
Chung, Kai Lai. 2000. <em>A Course in Probability Theory</em>. Third. Elsevier.
</div>
<div id="ref-copeland1977bias" class="csl-entry" role="listitem">
Copeland, Karen T, Harvey Checkoway, Anthony J McMichael, and Robert H Holbrook. 1977. <span>“Bias Due to Misclassification in the Estimation of Relative Risk.”</span> <em>American Journal of Epidemiology</em> 105 (5): 488–95.
</div>
<div id="ref-correa1995bias" class="csl-entry" role="listitem">
Correa-Villaseñor, Adolfo, Walter F Stewart, Francisco Franco-Marina, and Hui Seacat. 1995. <span>“Bias from Nondifferential Misclassification in Case-Control Studies with Three Exposure Levels.”</span> <em>Epidemiology</em> 6 (3): 276–81.
</div>
<div id="ref-dahabreh2019extending" class="csl-entry" role="listitem">
Dahabreh, Issa J, and Miguel A Hernán. 2019. <span>“Extending Inferences from a Randomized Trial to a Target Population.”</span> <em>European Journal of Epidemiology</em> 34 (8): 719–22.
</div>
<div id="ref-dawid1979conditional" class="csl-entry" role="listitem">
Dawid, A Philip. 1979. <span>“Conditional Independence in Statistical Theory.”</span> <em>Journal of the Royal Statistical Society: Series B (Methodological)</em> 41 (1): 1–15.
</div>
<div id="ref-dosemeci1990does" class="csl-entry" role="listitem">
Dosemeci, Mustafa, Sholom Wacholder, and Jay H Lubin. 1990. <span>“Does Nondifferential Misclassification of Exposure Always Bias a True Effect Toward the Null Value?”</span> <em>American Journal of Epidemiology</em> 132 (4): 746–48.
</div>
<div id="ref-von2007strengthening" class="csl-entry" role="listitem">
Elm, Erik von, Douglas G Altman, Matthias Egger, Stuart J Pocock, Peter C Gøtzsche, and Jan P Vandenbroucke. 2007. <span>“The Strengthening the Reporting of Observational Studies in Epidemiology (STROBE) Statement: Guidelines for Reporting Observational Studies.”</span> <em>The Lancet</em> 370 (9596): 1453–57.
</div>
<div id="ref-freedman1990impact" class="csl-entry" role="listitem">
Freedman, Laurence S, Arthur Schatzkin, and Yohanan Wax. 1990. <span>“The Impact of Dietary Measurement Error on Planning Sample Size Required in a Cohort Study.”</span> <em>American Journal of Epidemiology</em> 132 (6): 1185–95.
</div>
<div id="ref-goldberg1975effects" class="csl-entry" role="listitem">
Goldberg, Judith D. 1975. <span>“The Effects of Misclassification on the Bias in the Difference Between Two Proportions and the Relative Odds in the Fourfold Table.”</span> <em>Journal of the American Statistical Association</em> 70 (351): 561–67.
</div>
<div id="ref-gullen1968effects" class="csl-entry" role="listitem">
Gullen, Warren H, Jacob E Bearman, and Eugene A Johnson. 1968. <span>“Effects of Misclassification in Epidemiologic Studies.”</span> <em>Public Health Reports</em> 83 (11): 914–18.
</div>
<div id="ref-hernan2004structural" class="csl-entry" role="listitem">
Hernán, Miguel Á, Sonia Hernández-Dı́az, and James M Robins. 2004. <span>“A Structural Approach to Selection Bias.”</span> <em>Epidemiology</em> 15 (5): 615–25.
</div>
<div id="ref-moher2001consort" class="csl-entry" role="listitem">
Moher, David, Kenneth F Schulz, Douglas G Altman, Matthias Egger, Frank Davidoff, Diana Elbourne, Peter C. Gøtzsche, Thomas Lang, and CONSORT Group. 2001. <span>“The <span>CONSORT</span> Statement: Revised Recommendations for Improving the Quality of Reports of Parallel-Group Randomized Trials.”</span> <em>Annals of Internal Medicine</em> 134 (8): 657–62.
</div>
<div id="ref-newell1962errors" class="csl-entry" role="listitem">
Newell, David J. 1962. <span>“Errors in the Interpretation of Errors in Epidemiology.”</span> <em>American Journal of Public Health</em> 52 (11): 1925–28.
</div>
<div id="ref-newell1963note" class="csl-entry" role="listitem">
Newell, DJ. 1963. <span>“Note: Misclassification in 2 x 2 Tables.”</span> <em>Biometrics</em> 19 (1): 187–88.
</div>
<div id="ref-rogot1961note" class="csl-entry" role="listitem">
Rogot, Eugene. 1961. <span>“A Note on Measurement Errors and Detecting Real Differences.”</span> <em>Journal of the American Statistical Association</em> 56 (294): 314–19.
</div>
<div id="ref-rothman2008modern" class="csl-entry" role="listitem">
Rothman, Kenneth J, Sander Greenland, and Timothy L Lash. 2008. <em>Modern Epidemiology</em>. Lippincott Williams &amp; Wilkins.
</div>
<div id="ref-rubin1956use" class="csl-entry" role="listitem">
Rubin, Theodore, Joseph Rosenbaum, and Sidney Cobb. 1956. <span>“The Use of Interview Data for the Detection of Associations in Field Studies.”</span> <em>Journal of Chronic Diseases</em> 4 (3): 253–66.
</div>
<div id="ref-sorahan1994non" class="csl-entry" role="listitem">
Sorahan, Tom, and Mark S Gilthorpe. 1994. <span>“Non-Differential Misclassification of Exposure Always Leads to an Underestimate of Risk: An Incorrect Conclusion.”</span> <em>Occupational and Environmental Medicine</em> 51 (12): 839–40.
</div>
<div id="ref-vandenbroucke2007strengthening" class="csl-entry" role="listitem">
Vandenbroucke, Jan P, Erik von Elm, Douglas G Altman, Peter C Gøtzsche, Cynthia D Mulrow, Stuart J Pocock, Charles Poole, James J Schlesselman, Matthias Egger, and Strobe Initiative. 2007. <span>“Strengthening the Reporting of Observational Studies in Epidemiology (STROBE): Explanation and Elaboration.”</span> <em>Annals of Internal Medicine</em> 147 (8): W–163.
</div>
<div id="ref-verkerk1992non" class="csl-entry" role="listitem">
Verkerk, PH, and SE Buitendijk. 1992. <span>“Non-Differential Underestimation May Cause a Threshold Effect of Exposure to Appear as a Dose-Response Relationship.”</span> <em>Journal of Clinical Epidemiology</em> 45 (5): 543–45.
</div>
<div id="ref-wacholder1995non" class="csl-entry" role="listitem">
Wacholder, Sholom, Patricia Hartge, Jay H Lubin, and Mustafa Dosemeci. 1995. <span>“Non-Differential Misclassification and Bias Towards the Null: A Clarification.”</span> <em>Occupational and Environmental Medicine</em> 52 (8): 557.
</div>
<div id="ref-walker1988analysis" class="csl-entry" role="listitem">
Walker, Alexander M, Johan P Velema, and James M Robins. 1988. <span>“Analysis of Case-Control Data Derived in Part from Proxy Respondents.”</span> <em>American Journal of Epidemiology</em> 127 (5): 905–14.
</div>
<div id="ref-yland2022misconceptions" class="csl-entry" role="listitem">
Yland, Jennifer J, Amelia K Wesselink, Timothy L Lash, and Matthew P Fox. 2022. <span>“Misconceptions about the Direction of Bias from Nondifferential Misclassification.”</span> <em>American Journal of Epidemiology</em> 191 (8): 1485–95.
</div>
</div>
</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p> These tests are in the top left half of a receiver operating characteristic (ROC) plot from <a href="condprob.html#sec-roc" class="quarto-xref"><span>Section 2.3.2</span></a>, which has <span class="math inline">\(1 - \spec_D\)</span> is the horizontal axis and <span class="math inline">\(\sens_D\)</span> is the vertical axis. A test with <span class="math inline">\(\sens_D = 1 - \spec_D\)</span> (on the diagonal of the ROC plot) is a useless test. A test with <span class="math inline">\(\sens_D &lt; 1 - \spec_D\)</span> (in the bottom right half of an ROC plot) is worse than useless, but it can be redeemed by swapping the definitions of <span class="math inline">\(\Tplus\)</span> and <span class="math inline">\(\Tminus\)</span>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p> The <em>continuous mapping theorem</em> says that if a statistic <span class="math inline">\(\hat{\theta}_n \rightarrow \theta\)</span> in probability and <span class="math inline">\(f\)</span> is a continuous function in a neighborhood of <span class="math inline">\(\theta\)</span>, then <span class="math inline">\(f(\hat{\theta}_n) \rightarrow f(\theta)\)</span> in probability. Convergence in probability can be replaced with convergence in distribution or convergence almost surely <span class="citation" data-cites="chung2000course">(<a href="references.html#ref-chung2000course" role="doc-biblioref">Chung 2000</a>)</span>. Here, the statistic is <span class="math inline">\(\hat{p}_1 - \hat{p}_0\)</span>, which converges to <span class="math inline">\(p_1 - p_0\)</span>, and the function is <span class="math inline">\(f(v) = v^2\)</span>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p> As with a test for disease, a test for exposure with <span class="math inline">\(\sens_X + \spec_X = 1\)</span> would be a useless test (on the diagonal of an ROC curve) and a test with <span class="math inline">\(\sens_X + \spec_X &lt; 1\)</span> would need to have the definitions of <span class="math inline">\(\Tplus_X\)</span> and <span class="math inline">\(\Tminus_X\)</span> reversed.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p> Case control studies typically use the odds ratio <span class="math inline">\(\odds(\pi_1) / \odds(\pi_0)\)</span>, not the difference <span class="math inline">\(\pi_1 - \pi_0\)</span>, to compare the exposure prevalences in cases and controls. The difference between the prevalences is being used here only to establish that a hypothesis test of the independence of <span class="math inline">\(X\)</span> and <span class="math inline">\(D\)</span> based on misclassified data has the correct significance level.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p> In causal inference, selection bias can threaten both the internal and external validity of a study. It can cause an apparent association between <span class="math inline">\(X\)</span> and <span class="math inline">\(D\)</span> within the study sample that does not represent a causal effect <span class="citation" data-cites="hernan2004structural">(<a href="references.html#ref-hernan2004structural" role="doc-biblioref">Hernán, Hernández-Dı́az, and Robins 2004</a>)</span>.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p> We avoid use of the term “study population” because it sometimes refers to the study sample and sometimes to the eligible population.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./studydesign.html" class="pagination-link" aria-label="Cohort and Case-Control Studies">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Cohort and Case-Control Studies</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./cohort.html" class="pagination-link" aria-label="Measures of Association in Cohort Studies">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Measures of Association in Cohort Studies</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>